### ISSUE TITLE
:SearchInColumn not working in last column

### ISSUE THREAD

**Issue by norival** [chrisbra/csv.vim#100]
Hi!

I'm using this plugin with NeoVim and the `SearchInColumn` command doesn't seem to work when searching within the last column of the file.
This happens either when the cursor is in the column or by specifiying the column number in the command.

Thanks!

**Comment by Norival** [comment]
Hi again,

This seems to happen only when the columns are visually arranged by `ArrangeColumns`, otherwise it works just fine.

**Comment by chrisbra** [comment]
what is the output of `:echo @/`

**Comment by Norival** [comment]
Here is the output of `:echo @/` after searching for the term `public` in the last column:

`^\%([^,]*\%(,\|$\)\)\{4\}\zs\%(public\)\ze`

**Comment by chrisbra** [comment]
that is with a 5 column csv file? I guess `^\%([^,]*\%(,\|$\)\)\{4\}\s*\zs\%(public\)\ze` works then?

**Comment by norival** [comment]
Yes, it is a 5 column csv file.
And yes, searching for `^\%([^,]*\%(,\|$\)\)\{4\}\s*\zs\%(public\)\ze` works fine! :)

**Comment by chrisbra** [comment]
okay, please test current head. thanks.

**Comment by norival** [comment]
It works fine now.
Thanks for the update :)
