### ISSUE TITLE
CSVDeleteColumn /ptrn only searching within text, not metacharacters ^,$

### ISSUE THREAD

**Issue by cometsong** [chrisbra/csv.vim#101]
I've been attempting to use `CSVDeleteColumn /ptrn` to remove all columns that begin a character or a set of, by entering `/^ptrn` however it does not match any columns, but *does* show msg "CSV: 1 column deleted".  

Remove the `^` and it matches many of them that contain the string, deletes all matching columns.  Same when using `/ptrn$`

I do update to the latest version of the plugin on a regular basis, fyi.

Tips?
*Thanks!*

**Comment by chrisbra** [comment]
sorry, did not see this issue earlier. Is your problem, das `/^pattern` does not match but the plugin messages a positive message?

**Comment by cometsong** [comment]
Perfect! Thanks!

**Comment by cometsong** [comment]
Und auch, vielen Dank!
