### ISSUE TITLE
open file with no extension

### ISSUE THREAD

**Issue by yuejuny** [chrisbra/csv.vim#102]
when opening file without extension, vim could not identify the file content as comma separated file. although it is perfectly comma separated. anything I should do in the set up parameter so that this plugin can work properly in this case?

**Comment by chrisbra** [comment]
Hi yuejun!

On Mi, 25 Jan 2017, yuejun wrote:

> when opening file without extension, vim could not identify the file content as comma separated file. although it is perfectly comma separated. anything I should do in the set up parameter so that this plugin can work properly in this case?

Not really. If the name is always the same, you could setup an 
autocomand for that, see :h new-filetype

**Comment by yuejuny** [comment]
thank you for the quick response. 
the filenames are random and usually do not have extension.
For now, I manually rename them to add .csv in the file name.
