### ISSUE TITLE
How to convert crosstab format to straight table format in csv.vim?

### ISSUE THREAD

**Issue by sami10007** [chrisbra/csv.vim#108]
I am thinking if there any support for this basic task directly in csv.vim because I need to do the task often. I can do it in R and Vim visual mode/..., but would like to do it directly in csv.vim. Example data of crosstab format data 
```
,A,,B,,C,,D,,E,,F,
Field,time,T,time,T,time,T,time,T,time,T,time,T
Acute,0,0,8.3,1,7.5,1,8.6,2,0,0,8.3,4
Ane,9,120,7.7,26,7.9,43,7.8,77,7.9,60,8.2,326
```

**Comment by chrisbra** [comment]
I am not sure I understand. What would you like to do with the crosstab data?

**Comment by sami10007** [comment]
To convert it o the straight format:

```
Field,time,T,
Acute,0,0,A
Ane,9,120,A
Acute,8.3,1,B
Ane,7.7,26,B
Acute,7.5,1,C
Ane,7.9,43,C
Acute,8.6,2,D
Ane,7.8,77,D
Acute,0,0,E
Ane,7.9,60,E
Acute,8.3,4,F
Ane,8.2,326,F
```

**Comment by chrisbra** [comment]
sorry, I don't understand the rule to transform the file

**Comment by sami10007** [comment]
The rule is 

1. have as many repeats of (Acute - Ane) as much you have separate variables (4 = Field, time, T, experiment) where experiment is the implicit first row in first table. 
2. split first table (rows 2->) as blocks ordered by (time & T). 
3. Paste the new list now one after another such that the new column (Acute -  Ane repeats) is at the left-hand-side.

**Comment by chrisbra** [comment]
is this some kind of a standard format?

**Comment by chrisbra** [comment]
anyhow, it looks like this is not easy or straight forward. It will take a while for me to implement this.

**Comment by sami10007** [comment]
Yes, it is a standard format used in many statistics and business statistics programs. 

Please, let me know if you need any assistance to write the algorithm.

**Comment by chrisbra** [comment]
So the first 2 lines are kind of header lines that describe how the "CSV" file looks like? Is it always 2 header lines or can it be more?

**Comment by chrisbra** [comment]
no followup, closing.
