### ISSUE TITLE
Max length of items in a column

### ISSUE THREAD

**Issue by mikeyw** [chrisbra/csv.vim#109]
Hi @chrisbra. Thanks for a great plugin!

Can you please add the ability to calculate the max length of items in a column?

For example, if you have the following values in a column:
mike
joseph
roger

The max length would be 6 (joseph)

**Comment by chrisbra** [comment]
You mean like for :AnalyzeColumn?

**Comment by mikeyw** [comment]
I'm afraid not. While that command provides very useful information, what I'm looking for is the maximum length of the values in the column. How about adding a Length column to the output of the CSVAnalyze command?

Thanks!

**Comment by mikeyw** [comment]
Thanks @chrisbra !
