### ISSUE TITLE
error at vim startup 

### ISSUE THREAD

**Issue by RusAlex** [chrisbra/csv.vim#11]
how to avoid this error: 

``` shell
CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)
```

**Comment by naught101** [comment]
I get this error when using csv.vim with pathogen - I cloned the repo to `~/.vim/bundle/csv.vim`, and then try to open a `.csv` file, and get this message. I have nothing CSV-related in my `.vimrc`. Is there anything else that needs to be done to get this to work with pathogen?

**Comment by chrisbra** [comment]
Does `:h csv-syntax-error` help?

**Comment by naught101** [comment]
Hrm, yes, it does seem to - I misread the directions. It works only if `filetype plugin on` is before `syntax on`.  Is there a reason that it says "reverse the order", rather than just "make sure the syntax call comes after the plugin call"? I'd find the latter a lot less ambiguous.

**Comment by chrisbra** [comment]
Hi naught101!

On Di, 09 Jun 2015, naught101 wrote:

> Hrm, yes, it does seem to - I misread the directions. It works only if
> `filetype plugin on` is before `syntax on`.  Is there a reason that it
> says "reverse the order", rather than just "make sure the syntax call
> comes after the plugin call"? I'd find the latter a lot less
> ambiguous. 

No, if this is clearer, I'll fix the documentation.

Best,
Christian
-- 
Bei jedem Streit ziehe die Versöhnung stets dem leichtesten Siege vor.
		-- Georg Christoph Lichtenberg

**Comment by naught101** [comment]
Awesome. Vielen Dank :)
