### ISSUE TITLE
Add feature to constrain cursor to column when searching

### ISSUE THREAD

**Issue by fuzzybear3965** [chrisbra/csv.vim#110]
I find myself editing CSV files (which maintain students' grades) where I'd like to search for a string (student's name) in column X, but only modify a value (the grade) in column Y. It'd be really slick to have some session-level command (not filetype-/buffer-level) where, for that session, you can constrain the search over a set of columns and constrain the cursor to another column. I.e. `:ConstrainedSearchAndEdit([1,2,5], 3)` might fix the cursor to the third column while searching strings from columns 1,2, and 5.

**Comment by chrisbra** [comment]
It is not really possible in Vim to make only certain regions writable. Best thing to do is probably to use the csv plugin with my NrrwRgn plugin and also use the :SearchInCol command
