### ISSUE TITLE
Shift+V up does not work with plugin enabled

### ISSUE THREAD

**Issue by jeffzemla** [chrisbra/csv.vim#111]
To select multiple lines in Visual mode, I typically do `Shift+V <up>` (or `<down>`). The CSV plugin breaks this functionality. When I press `<up>` the current line is un-selected and I am put back in Normal mode. If I use `j` or `k` instead of `<up>` or `<down>` everything works as expected.

**Comment by chrisbra** [comment]
I cannot reproduce this. What is the output of `:verbose :xmap <up>` or `:verbose :vmap <up>`?

**Comment by jeffzemla** [comment]
`:verbose :xmap <up>` and :verbose :vmap <up>` both output the same:

>    <Up>        *@:<C-U>call <SNR>46_MoveCol(0, line(".")-v:count1)<CR>
>        Last set from ~/.vim/ftplugin/csv.vim

**Comment by chrisbra** [comment]
Hm, this is obviously mapped in CSVMappings(), however I still cannot reproduce this. Oh well, let's just remove the mapping in visual mode. Should be fixed now.

**Comment by jeffzemla** [comment]
It works, thank you!
