### ISSUE TITLE
ConvertData with numbered column fields to select specific columns?

### ISSUE THREAD

**Issue by Henri-Lo** [chrisbra/csv.vim#113]
You have CSV data like

```
TakeMe,NotMe,TakeMe3,TakeMe4,NotMe5,NotMe6
1,2,3,4,5,6
11,22,33,44,55,66
```

I press `ConvertData <ENTER> <ENTER>` and now I want  to get this to 

```
TakeMe,TakeMe3,TakeMe4
1,3,4
11,33,44
```

In order to solve this problem, we need ask some one the following:

1. How can I specify named columns such has first column %1s? (I could use numbering to select columns)
2. How can I ignore a column? (I could also put some market in front of %s to ignore it)
3. Other ways to preprocess the data in CSV.vim?

**Comment by chrisbra** [comment]
You don't want to convert the csv data, but rather delete specific columns. So how about `for i in range(100,1,-2) | exe "DeleteColumn" i | endfor`
