### ISSUE TITLE
not working in mac

### ISSUE THREAD

**Issue by mcheung63** [chrisbra/csv.vim#114]
Not working in mac, please help. my error "E492: Not an editor command: WhatColumn"

/Users/peter/.vim>cat ~/.vim/filetype.vim 
if exists("did_load_csvfiletype")
  finish
endif
let did_load_csvfiletype=1

augroup filetypedetect
  au! BufRead,BufNewFile *.csv,*.dat	setfiletype csv
augroup END
/Users/peter/.vim>

**Comment by chrisbra** [comment]
how did you install the plugin?

**Comment by chrisbra** [comment]
closing for being unresponsive
