### ISSUE TITLE
Disabling CSV.vim with large files with LargeFile ext or some other approach?

### ISSUE THREAD

**Issue by Henri-Lo** [chrisbra/csv.vim#119]
I found out this extension `http://www.vim.org/scripts/script.php?script_id=1506` `LargeFile`  which basically disables all extensions when the size of the file becomes larger than 100MB or your specified threshold. This is particularly useful with CSV.vim and I know that there is some project to integrate CSV.vim with other packages.

**What is the best approach to work with large files with CSV.vim? Using the LargeFile extension or some other combination of extensions?**

**Comment by chrisbra** [comment]
unfortunately, largefile disables csv.vim which makes sense, since for large files the syntax highlighting can be slow. I am not sure what exactly you are looking for.

**Comment by Henri-Lo** [comment]
@chrisbra there is a bundle of Vim plugins where I think you was also contributing to and I would like to have this plugin in that bundle. Is it possible to have this in the bundle? Can you remember the name of the bundle?

**Comment by chrisbra** [comment]
not that I know of. csv.vim used to be part of vim-polyglot, but they removed it for whatever reason. Don't know of other distributions that include it.
