### ISSUE TITLE
Need some help in using this perfect plugin

### ISSUE THREAD

**Issue by TravelTrader** [chrisbra/csv.vim#121]
I do not want to use this plugin every time I open a csv-file.
Is there a possibility to open a csv-file in vi and then change the view to the plugin? Like **enable it during working in vi**?

Thank you for all hints and tipps
your TravelTrader

**Comment by chrisbra** [comment]
simply do `:set filetype=text` to disable the plugin temporarily and set it back to csv when you want it to be enabled.

**Comment by TravelTrader** [comment]
It doesn't work. I do not get the plugin working before trying your hint:

_vim = VIM - Vi IMproved version 7.4.8056
macOS_

- git clone to the folder ~/.vim/
- inserted `filetype plugin on` in vimrc
- created filetype.vim

.. nothing when opening csv-files .. I'm sorry ..

**Comment by chrisbra** [comment]
By default the plugin should do everything you need automatically (and you shouldn't need to do any extra work besides putting `filetype plugin on`. If you are not using a plugin manager, I suggest to open the file csv.vmb with vim and simply source it (`:source %`). That puts every file in its required location. Nowadays using plugin managers is usually even simpler.

**Comment by TravelTrader** [comment]
Thanks a lot for your help.
After typing `source ~/.vim/csv.vmb`I got an error:

```"~/.vim/csv.vmb" [New File]
Error detected while processing function vimball#Vimball:
line   10:
(Vimball) The current file does not appear to be a Vimball!
Press ENTER or type command to continue
```

Do you have an idea what I can do?

**Comment by chrisbra** [comment]
hm, strange. That error happens only if the first line does not say `" Vimball Archiver`. Did you open the file in Vim before trying to source it? Else please make sure it is the complete file as you can download it from github. You can download it using e.g. wget like this: `wget https://raw.githubusercontent.com/chrisbra/csv.vim/master/csv.vmb` 

Also I have just uploaded a newly generated vimball that works with my version.

**Comment by TravelTrader** [comment]
_Yes, very strange. I'm new in vim plugins but I program a lot and use linux systems since I was a child. I feel like I'm too stupid for that. Therefore I asked you for help._

I typed the `git clone` command from `~/.vim`. Maybe that was the mistake? But where should I put it?

Now I used your `wget`-command to put the `csv.vim` file directly in the `.vim`-folder. After `:source ...` it extracted files and there was no error. But I think that was one of the possibilities I tried before asking you.
It doesn't work with a csv-file ... could the macOS be the reason?

**Comment by chrisbra** [comment]
yeah, it probably shouldn't be cloned directly below `~/.vim`. Vim 8 has the `pack` feature for that, you would then clone it into `~/.vim/pack/dist/start` and be done with it. 

So you have the files `~/.vim/ftplugin/csv.vim`? And it still does not work when editing `*.csv` files? That is really strange. If you edit such a file, what is the output of `:verbose set ft?`

**Comment by TravelTrader** [comment]
> So you have the files ~/.vim/ftplugin/csv.vim? And it still does not work when editing *.csv files?

Yes.

> That is really strange. If you edit such a file, what is the output of :verbose set ft?

It's:
```
filetype=csv
Last set from ~/.vim/ftdetect/csv.vim
```

Do you have another idea?
Or do you have a csv file woking with your plugin at your vi? Maybe it's because of my csv files? I tested different ones, some from websites.

**Comment by TravelTrader** [comment]
After writing this I tested another 5 ones and with one file I got
`CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)`
directly before it opened.

**Comment by chrisbra** [comment]
hm, if you enter the commandline and type `:CSV` and then press CTRL-D, do you see a bunch of :CSV commands (like :CSVArrangeColumn, or `:CSVInit`)? If so, then the plugin is working and just the syntax highlighting is broken.

**Comment by TravelTrader** [comment]
With `:csv`and Return I get `E492: Not an editor command: csv`.
Or typing `:csv` there is another `:csv` on one more line for each CTRL-D.
It is not working? Seems mysterious ...

**Comment by chrisbra** [comment]
capitalize the csv please, so `:CSV<CTRL-D>`

**Comment by TravelTrader** [comment]
Only `CSVTable`. Not more.

**Comment by chrisbra** [comment]
That is not right. Can you please run `vim -V9debug.txt file.csv`? close vim and post the debug.txt file somewhere please.

**Comment by TravelTrader** [comment]
I'm curious: [https://www.dropbox.com/s/1hhptwsdvuhi1sx/debug.txt?dl=0](url)

**Comment by TravelTrader** [comment]
I'm sorry, but did you checked the debug file?

**Comment by chrisbra** [comment]
strange, nothing very unordinary?
If you open a csv file manually and do `:unlet! b:did_ftplugin` `:source /Users/company/.vim/ftplugin/csv.vim` does it work?

**Comment by chrisbra** [comment]
you do not have by any chance several csv plugins installed?

**Comment by TravelTrader** [comment]
After your line it says `E488: Trailing characters`.

And no, I do not have anything on for csv-files. Maybe too many files from your plugin?

**Comment by chrisbra** [comment]
those were supposed to be 2 separated commands. Please do first:

    :unlet! b:did_ftplugin

followed by:

    :source /Users/company/.vim/ftplugin/csv.vim

**Comment by TravelTrader** [comment]
Sorry, after these two lines there was no error displayed. And the .csv was colored (first line red and the other line red and orange changing for the columns). Nice, but I think there should be more separation like borders and auto-tabs ..?

Is this a first success?

**Comment by chrisbra** [comment]
So the plugin works in principle. I don't understand why your vim does not load it. Do you have `eventignore` option set? 

> Nice, but I think there should be more separation like borders 

Try `%CSVAutoArrange`

> and auto-tabs ..?

Not sure what you mean with that.

**Comment by TravelTrader** [comment]
After all your tipps when opening, I see
`CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)`
and after pressing enter it looks like this:
![vim-csv-sample](https://user-images.githubusercontent.com/36788177/37333570-f4b89f30-26a9-11e8-9363-1417ca6a6640.jpg)

Is this, what it should look like?
I thought it will look like
![vim-csv-original](https://user-images.githubusercontent.com/36788177/37333705-4efa94bc-26aa-11e8-8590-dac594227660.jpg)

**Comment by chrisbra** [comment]
> CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)

That usually happens, when the syntax script is loaded before the filetype plugin. The help has a section about it:
https://github.com/chrisbra/csv.vim/#syntax-error-when-opening-a-csv-file

Your second screenshot uses the coneal feature to display a spread sheet like view and uses custom highlighting. This is also described in the help: https://github.com/chrisbra/csv.vim/#concealing

**Comment by chrisbra** [comment]
I think I made recently an error, that made the automatic plugin dettection not work. Please update the plugin and you shouldn't see the error anymore. Closing.
