### ISSUE TITLE
plugin loaded during runtime does not have the `CSVInit` command

### ISSUE THREAD

**Issue by fmv1992** [chrisbra/csv.vim#124]
First of all thanks for this plugin :)

The issue is that if the plugin is loaded optionally (eg in `~/.vim/packpathdir/pack/one_plugin/opt/`) it does not have the `CSVInit` command.

I would like to run it on demand.

**Comment by chrisbra** [comment]
It is a filetype plugin. The `CSVInit` command will only ever be available for a csv file once the plugin is loaded.

**Comment by fmv1992** [comment]
Thanks.

Very nice to see some small csvs with `:%CSVArrangeColumn`.

Keep up the good work!

Closing this issue.
