### ISSUE TITLE
How to clear filters?

### ISSUE THREAD

**Issue by serussell** [chrisbra/csv.vim#126]
I can't figure out how to clear filters once they're set; there doesn't seem to be anything in the documentation about how to undo them, aside from reloading the file -- which requires saving the file, which I might not want to do.  Can I request instructions in the docs about this?

**Comment by chrisbra** [comment]
It is mentioned briefly here https://github.com/chrisbra/csv.vim#normal-mode-commands
Use `<BS>` to remove one filter after the other.

**Comment by serussell** [comment]
@chrisbra thanks, that works!
