### ISSUE TITLE
Insert the result of a SumCol?

### ISSUE THREAD

**Issue by serussell** [chrisbra/csv.vim#127]
`SumCol` is nice!  How do I use the value?  I'd like to insert it into a cell.  It, and `CSVSumCol`, don't appear to be functions that can be used with the `"=` register.

**Comment by chrisbra** [comment]
The `CSVSumCol()` function is available specifically for that. I just tested it, Enter Insert Mode, `<C-R>=CSVSumCol(1, '', 2,4)<cr>` Successfully inserted the result of Column1, lines 2-4 into the line.

**Comment by serussell** [comment]
@chrisbra is the function new?

```
=CSVSumCol(2, '', 2, 20)
E117: Unknown function: CSVSumCol
Press ENTER or type command to continue
E15: Invalid expression: CSVSumCol(2, '', 2, 20)
```

Even if that worked for me, it's more work than just re-typing in the value. Can `SumCol` be modified to store the result in a register, e.g. "+?

Sorry for asking the question; I have zero vimscript-fu.
