### ISSUE TITLE
Can I turn off this plugin for tsv?

### ISSUE THREAD

**Issue by Chiel92** [chrisbra/csv.vim#128]
I would like to use this plugin only for csv, and not for tsv. But if I enable this plugin, it automatically sets the filetype to csv based on the filename extension `.tsv`. Is there a way to work around this?

**Comment by chrisbra** [comment]
Remove the `*.tsv` from https://github.com/chrisbra/csv.vim/blob/master/ftdetect/csv.vim

**Comment by chrisbra** [comment]
you could in theory just change that file on your side after cloning. No need to fork it. And i doubt, that it will change often. It hasn't been in a long time and before the last change it was long time not touched.

Alternatively, you can check, if any of the methods described at `:h new filetype` help overriding your filetype.
