### ISSUE TITLE
Movement command L at end of row moves southeast if next row has more cells

### ISSUE THREAD

**Issue by zestyping** [chrisbra/csv.vim#137]
Thank you for creating this wonderful plugin!  It does a lot of great things.  However, I noticed some strange behaviour with the movement commands that is probably not what you intended.  I'll open new issues for each anomalous behaviour that I find.  I hope this helps!

### Description

When the next row has fewer columns than the current row, pressing `L` moves to the first cell of the next row.  I assume this is as designed, since `H` does the opposite, returning to the last cell of the preceding row.

But when the next row has more columns than the current row, pressing `L` moves diagonally down and to the right one cell.  This seems wrong; pressing `L` should always do the opposite of `H`.

### Example

```
a,b,c
d,e,f,g,h
i,j,k
```

Actual behaviour: Place the cursor on `c`.  Press `L`.  The cursor moves to `g`.  Press `H`.  The cursor moves to `f`.

Expected behaviour: Place the cursor on `c`.  Press `L`.  The cursor moves to `d`.  Press `H`.  The cursor returns to `c`.

**Comment by chrisbra** [comment]
thanks for the nice feedback. I think the problem mentioned has been fixed by  58a77e41bfa9b133
