### ISSUE TITLE
Movement command L at end of row does nothing if cell contains 2 or more characters

### ISSUE THREAD

**Issue by zestyping** [chrisbra/csv.vim#141]
### Description

When the cursor is positioned on the last character of a row, and the last cell in the row has 2 or more characters, pressing `L` has no effect.  Given that, in other conditions, `H` and `L` wrap around to the last cell of the preceding row or the first cell of the next row, pressing `L` should probably move to the beginning of the next row.

### Example

```
ab,cd
e,f,g,h
```

Actual behaviour: Place the cursor on `d`. Press `L`.  Nothing happens.

Expected behaviour: Place the cursor on `d`. Press `L`. The cursor moves to `e`.

**Comment by chrisbra** [comment]
Hm, thanks. I think the problem is, that the number of max columns is not correct for line 2. So let's calculate it correctly.

**Comment by zestyping** [comment]
@chrisbra Wow!  Thank you for fixing all of these issues so fast!  I really appreciate this plugin.
