### ISSUE TITLE
How to set default csv delimiter

### ISSUE THREAD

**Issue by sheerun** [chrisbra/csv.vim#142]
Hello,

I want to leave auto-detecting delimiter, but I also want to set default delimiter if auto-detecting fails, so I don't get `CSV: No delimiter found. See :h csv-delimiter to set it manually!` message and I don't need to set default delimiter manually. Is setting such fallback possible?

**Comment by byteptr** [comment]
I have same problem, I added let g:csv_delimiter=';' into my vimrc file with no luck, and neither :h csv-delimiter works. Im using gvim 8.2.13.13 under windows 10. Im considering trying to hack the plugin...

**Comment by chrisbra** [comment]
I think it needs to be `let g:csv_delim=';'`.

Another possibility would perhaps be a filetype autocommand like `:let b:delimiter=';'`
