### ISSUE TITLE
Plugin fails to load properly. 

### ISSUE THREAD

**Issue by sambeaux** [chrisbra/csv.vim#144]
It looks like it's loading the syntax, or at least CSV files are highlighted the way I would expect them... I get the following error when I launch vim:

Error detected while processing /home/sja/.vim/ftplugin/csv.vim:
line   29:
E117: Unknown function: csv#Init
CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)

I've moved my syntax statement to the bottom of my .vimrc, but that didn't help. I'm unable to use any of the new commands, like ArrangeColumn. Any help would be greatly appreciated.

**Comment by chrisbra** [comment]
How have you installed the plugin?

**Comment by sambeaux** [comment]
I used:

make install

I see now that the autoload folder did not get copied into my $HOME/.vim
folder. Once I copied that over, it seems to be working.
Sorry for the trouble.

You wouldn't happen to be a sed wizard by any chance? I have a particularly
vexing problem that I'm having trouble with.

Sam Alleman
LSP Instructor #484
(337) 205-3216

**Comment by Jeklah** [comment]
I am also getting this error. I have copied autoload folder into ~/.vim and it still isn't working.

**Comment by chrisbra** [comment]
can you please show the directory structure of where each part of the plugin resides?

**Comment by Jeklah** [comment]
Nevermind. I ran CSVInit and it's working now. Disregard my comments, thanks for the plugin!

**Comment by Jeklah** [comment]
It's in ~/.vim/bundle/csv
Also the autoload folder has been copied to ~/.vim/ after make and make install.

**Comment by Jeklah** [comment]
Ok so it seems to be you have to run CSVTable on a csv file before any of the CSV functions are available including CSVInit.

**Comment by chrisbra** [comment]
No  that is not the case. Is the file extension csv?

**Comment by Jeklah** [comment]
ah, i didn't have the filetype.vim file under ~/.vim/
all is working as expected now. thanks for replying though.

**Comment by Jeklah** [comment]
yes it was

**Comment by Jeklah** [comment]
Sorry to come back to this, but I've encountered it again, the file is csv but only CSVTable shows up.
I went back and opened the other file I've sent you, that works fine still.
This is the file it doesn't seem to be recognising.
[fifa19data.zip](https://github.com/chrisbra/csv.vim/files/4309472/fifa19data.zip)

**Comment by chrisbra** [comment]
seems to be working for me. Again, how have you installed the plugin? I am using vims native packages and have it available in `~/.vim/pack/minpac/start/csv.vim`. This works without problems and detects my csv files just fine.

**Comment by Jeklah** [comment]
I used the git clone command as per pathogen installation instructions.
Then I went into vim and did :PluginInstall csv
next I went into .vim/bundle/csv and did make and make install.
Next I copied autoload folder from .vim/bundle/csv to .vim
Then I made the filetype.vim file and put that in .vim/
Added set filetype on in .vimrc.local.

That's how I did it, in order as best as I can remember.

**Comment by Jeklah** [comment]
I'm out atm but can post tree structure when am home if you would like

**Comment by leonryrko** [comment]
I had a similar issue where I would always get the error `CSV Syntax:Invalid column pattern, using default pattern %([^,]*,|$)` when opening a .csv file and, moreover, none of the commands could be called, except for `:CSVTable`.
The issue was that installing the plugin using vim-plug wasn't enough. I needed to source `csv.vmb` manually as explained on the [VIM script website](https://www.vim.org/scripts/script.php?script_id=2830).

**Comment by chrisbra** [comment]
let's close it.
