### ISSUE TITLE
auto-width for columns?

### ISSUE THREAD

**Issue by prankousky** [chrisbra/csv.vim#145]
Hi,

is it possible to set columns automatically to each columns maximum value? For example

before:
```
ip|device|note
192.168.100.1|pc|well a pc
```
after:
```
ip                    |device|note
192.168.100.1|pc       |well a pc
```

and if adding another line with a longer device name
```
ip                    |device         |note
192.168.100.1|pc                |well a pc
192.168.100.2| homeserver|the home server
```
etc.?

I am currently using `sc-im` for csv files, which is alright, but I'd prefer to use `vim` instead. If this plugin could stretch columns in such a way, it'd be perfect. Thanks in advance for your support :)

**Comment by thinrope** [comment]
Did you try `:%CSVArrangeColumn!` ?

**Comment by prankousky** [comment]
That was it, thank you.
