### ISSUE TITLE
ArrangeCol for multi-byte text

### ISSUE THREAD

**Issue by thinrope** [chrisbra/csv.vim#146]
I know it will be challenging, but can you make ArrangeCol work properly with multi-byte characters (or shall I say double width?) such as Japanese. I guess the trick is when text contains single and double width mixed within a column. Or may be not (just tested just with lines 1&3 and it does not work).

Have a look at the test case (you'll need some Unicode font to see it).
I can help testing/debugging if you accept the challenge :-D
FYI, there is wide space (not in this data) as well: https://www.compart.com/en/unicode/U+3000

Also, running `:%ArrangeColumn! ` multiple times keeps adding space at each column, is that expected?

```csv
C1,C2,C3
test1,test2,test3
本,日本,日本語
消しゴム,Japan 日本,ｚｅｎｎｋａｋｕ
```

**Comment by chrisbra** [comment]
I thought it does already handle multibyte characters, although I have never tested with double width characters
