### ISSUE TITLE
Delimits tab characters, but result looks wrong

### ISSUE THREAD

**Issue by ekiefl** [chrisbra/csv.vim#148]
Hi,

csv.vim is clearly delimiting according to tab characters, but it does not replace them with `|` and ArrangeColumn does not do anything.

Here my cursor is on column 1:

![image](https://user-images.githubusercontent.com/8688665/68034774-58fd5b80-fc90-11e9-89c7-df8e079d3ca2.png)

Here its on cursor 2:

![image](https://user-images.githubusercontent.com/8688665/68034795-61ee2d00-fc90-11e9-877a-5d469513822a.png)

When I `:%s/\t/,/g` and then reopen the file, everything is dandy:

![image](https://user-images.githubusercontent.com/8688665/68034909-98c44300-fc90-11e9-9372-23c447f2fe3b.png)

Here are my settings:

```
let g:csv_highlight_column = 'y'
aug CSV_Editing
    au!
    au BufRead,BufWritePost *.csv :%ArrangeColumn
    au BufWritePre *.csv :%UnArrangeColumn
aug end

```

**Comment by chrisbra** [comment]
does it work correctly if you do `:set nolist`?

**Comment by ekiefl** [comment]
Yes!
