### ISSUE TITLE
Any option to remove the mapping of the <Space> key?

### ISSUE THREAD

**Issue by skamsie** [chrisbra/csv.vim#149]
I have my `<Space>` key mapped to `<Leader>` and then I have mappings using the leader key in normal mode. I see the plugin is mapping `n  <Space>     *@:<C-U>call csv#PrepareFolding(1, 0)<CR>` and none of my mappings with leader work anymore inside csv files... Any way to remove it?

**Comment by chrisbra** [comment]
Hi,
does the documentation help you?

https://github.com/chrisbra/csv.vim/blob/f8d24584b01cc72e1a3bee640099a7d9bae98102/doc/ft-csv.txt#L616-L621

**Comment by skamsie** [comment]
sure, thank you. I will close it :)
