### ISSUE TITLE
How to install csv.vim as optional plugin, using pack

### ISSUE THREAD

**Issue by andalou** [chrisbra/csv.vim#151]
I'm using vim 8.1.2351 on Windows 7.
I put csv under vimfiles\pack\bundle\opt\csv, and I did
:packadd csv
then I use a csv command, like :SumCol, but it doesn't load.
The package isn't loaded!
With other packages, even having autoload, installed as optional
plugins, there isn't any problem.

**Comment by chrisbra** [comment]
You need to use the packadd command before opening a csv file

**Comment by andalou** [comment]
It only works, if after doing 'packadd csv', and loading a file, which
hasn't necessarily the extension .csv, I do:
set ft=csv

I have a problem with the plugin, what is wrong with the following data
(without the dashes)?:

----------

29349,4817
384,1839
----------

After loading it, I always get:
CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)

No matter what separator I use, I always get the same message, but
afterwards I can use all the commands, like SumCol, etc.

**Comment by andalou** [comment]
It only works, if after doing 'packadd csv', and loading a file, which
hasn't necessarily the extension .csv, I do:
set ft=csv

I have a problem with the plugin, what is wrong with the following data
(without the dashes)?:

    ----------

    29349,4817
    384,1839
    ----------

After loading it, I always get:
CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)

No matter what separator I use, I always get the same message, but
afterwards I can use all the commands, like SumCol, etc.

**Comment by chrisbra** [comment]
how have you installed it? Have you looked at `:h csv-syntax-error`?
