### ISSUE TITLE
Error while loading tsv file

### ISSUE THREAD

**Issue by pkrog** [chrisbra/csv.vim#152]
When loading a tsv file I get the following error:
```
Error detected while processing function csv#Init:
line   84:
E119: Not enough arguments for function: csv#CalculateColumnWidth
line   86:
E121: Undefined variable: b:col_width
E116: Invalid arguments for function join(b:col_width, ',')
```
The TSV file is:
```
abc	def	ghi
1	2	a
3	4	b
5	6	c
```
It seems the function csv#CalculateColumnWidth() takes two arguments (second is `silent`) and is called with only one. I'll make a modification and propose a pull request.

**Comment by chrisbra** [comment]
should be fixed by #154
