### ISSUE TITLE
How to use csv plugin for file without .csv extension? 

### ISSUE THREAD

**Issue by programus** [chrisbra/csv.vim#156]
I have some very large CSV files to process, and I usually do something like this to save the load time. 

```
$grep 'pattern' xxx.csv | vim -
$head xxx.csv | vim -
```

I found the CSV plugin do not work in this case. 

Even I `:set syntax=csv` , it still doesn't work. 

Is there any way to enable CSV plugin even I open a buffer like this?

**Comment by chrisbra** [comment]
Do not use Set syntax but use :set  filetype

**Comment by programus** [comment]
@chrisbra Thank you very much! It works after I `:set filetype=csv` .
