### ISSUE TITLE
Locale error message on opening csv files 

### ISSUE THREAD

**Issue by joelmarty** [chrisbra/csv.vim#157]
I am having the following error message when opening a CSV file on MacOS:

```
Error detected while processing function csv#Init[19]..csv#GetDelimiter:
line   37:
E197: Cannot set language to "en_ES"
```

I guess the issue comes from [this part](https://github.com/chrisbra/csv.vim/blob/master/autoload/csv.vim#L445):
```
let lang=v:lang
if lang isnot# 'C'
	sil lang mess C
endif
```

and [that part](https://github.com/chrisbra/csv.vim/blob/master/autoload/csv.vim#L479):
```
        if lang != 'C'
            exe "sil lang mess" lang
        endif
```

**Comment by chrisbra** [comment]
It's probably the part further down where the language is restored. Not sure why you See this error, if the locale is en_ES one should be able to reset it

**Comment by joelmarty** [comment]
I forgot to mention I am using neovim, not vim so maybe it has to do with that.

**Comment by chrisbra** [comment]
so what does `:lang mess` return? And what is the output of `:echo v:lang`? And once you change it to `:lang mess C` can you correctly set it back to use `:lang mess <value>` (that is the value that your first `:lang mess` shows).

**Comment by joelmarty** [comment]
In an empty buffer:
`:lang mess` -> `Current messages language: "en_ES"`
`:echo v:lang` -> `en_ES`

```
:lang mess C # ok
:lang mess en_ES # E197: Cannot set language to "en_ES"
```

In a CSV file:
`:lang mess` -> `Current messages language: "C"`
`:echo v:lang` -> `C`

It looks like you are right. I am unsure why, but doing `locale -a` does not list `en_ES`.
That looks like a MacOS "feature".

**Comment by chrisbra** [comment]
Yeah, that in a csv file the locale is `C` is expected, as the csv plugin cannot switch back to your original locale. Unfortunately, switching is needed, to determine the number of delimiters correctly. It does so by parsing the output of a `:s` call, which of course depends on the locale.

Check if it works with Vim. If it does, report it to neovim. Changing the locales back should be possible. That is definitely a bug here. 

I am afraid, I can't fix this from the csv plugin. I can perhaps catch the error and output an error message, not sure that is helpful however.

**Comment by joelmarty** [comment]
I tried the following with Vim (8.0)
In an empty buffer:
- `:lang mess` -> `Current messages language: "C"`
- `:echo v:lang` -> `C`
- `:lang mess C` -> ok
- `:lang mess en_ES` -> `E197: Cannot set language to "en_ES"`

In a CSV file:
- Opening the file gives the following error: `CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)`
- `:lang mess` -> `Current messages language: "C"`
- `:echo v:lang` -> `C`
- `:lang mess en_ES` -> `E197: Cannot set language to "en_ES"`

**Comment by chrisbra** [comment]
if your current locale is `C`, it shouldn't try to set the locale to `en_ES`.

**Comment by chrisbra** [comment]
> CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)

Please have a look at https://github.com/chrisbra/csv.vim/blob/master/doc/ft-csv.txt#L1684-L1698

**Comment by joelmarty** [comment]
> Please have a look at https://github.com/chrisbra/csv.vim/blob/master/doc/ft-csv.txt#L1684-L1698

That fixed it.

> if your current locale is C, it shouldn't try to set the locale to en_ES.

I believe this is MacOS specific, `locale` command yields the following:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

But the OS settings is set to `en_ES`:
```
$ defaults read -g AppleLocale
en_ES
$  defaults read -g AppleLanguages
(
    "en-ES",
    "es-ES"
)
```

So I guess it is not stricly a plugin error. Looking at the error I found out there are some well known issues with `gettext` on MacOS. Probably related to that, WDYT? Close this issue at your discretion.
