### ISSUE TITLE
:%ArrangeColumn does not work after opening a file

### ISSUE THREAD

**Issue by antoinemadec** [chrisbra/csv.vim#158]
Thanks for this amazing plugin!
I noticed a regression happening after: 3128891191d7e363d39cbe70b96281ec8d897bcb
This is working just fine: f8d24584b01cc72e1a3bee640099a7d9bae98102

```:%ArrangeColumn``` does not work right after a file has been open.
However, after moving the cursor down and up again, it works.

Vimrc:
```vim
call plug#begin('~/.vim/plugins')
Plug 'chrisbra/csv.vim''
call plug#end()
```

Failed on an up-to-date **neovim** and **vim8**.

Would it be easy to fix?

Thanks :smiley:

**Comment by chrisbra** [comment]
thanks for letting me know. Should work now again :)

**Comment by chrisbra** [comment]
Thanks for the nice feedback, I really appreciate this.

**Comment by antoinemadec** [comment]
That fixed the issue for me, thanks a lot!
