### ISSUE TITLE
CSVArrangeColumn aligning bug

### ISSUE THREAD

**Issue by Jeklah** [chrisbra/csv.vim#160]
I think I actually found a bug...as opposed to user misconfiguration...
![alignBug](https://user-images.githubusercontent.com/7274473/76260829-95e5ea00-6250-11ea-82d5-6ed1d10abf90.png)
if let b:csv_arrange_align='l*' or 'c*' this issue occurs, commas in values are being incorrectly turned into pipes.
if it is set to 'r*' it works:
![alignBugWorking](https://user-images.githubusercontent.com/7274473/76261029-fd9c3500-6250-11ea-8532-615881abefb0.png)

**Comment by Jeklah** [comment]
each line in the csv file its reading from starts with "" if that makes a difference.

**Comment by chrisbra** [comment]
Can you share the example please?

**Comment by Jeklah** [comment]
[allTheStations.zip](https://github.com/chrisbra/csv.vim/files/4309184/allTheStations.zip)

**Comment by Jeklah** [comment]
Have you managed to reproduce this? Just curious

**Comment by chrisbra** [comment]
I think I have noticed before. Might actually be a but in the syntax highlighting or more concrete in the regular expression used to detect different columns. Not sure there is an easy way to fix this.

**Comment by Jeklah** [comment]
Eh, is no big issue for me, I'll just use align right :)
At least I found an actual bug and not my misconfiguration this time 😅

**Comment by Jeklah** [comment]
I've just noticed this issue also occurs with aligning right, although strangely only the last column and only values over 1000.

![csvAlignRight](https://user-images.githubusercontent.com/7274473/76525570-fb5df480-6463-11ea-89b5-1be68299c6f0.png)
