### ISSUE TITLE
:%Substitute fails on last column ?

### ISSUE THREAD

**Issue by furicle** [chrisbra/csv.vim#161]
Given a file like
```
SAT|X144|INDIVIDUAL CO MONITOR|423.29|14|BS|||X144|X144
SAT|X767-PLUS|CO MONITOR,A.C. ECONO VERSION|2190.58|14|BS|||X767-PLUS|X767-PLUS

```

:%Substitute 9/[^0-9A-Z]//    

removes the dash in the ninth column

but it won't work if you do the same thing on the tenth column?
:%Substitute 10/[^0-9A-Z]//

No error, just doesn't replace the dash...

**Comment by chrisbra** [comment]
thanks. The regexes get tricky sometimes. Hopefully it doesn't break for someone else.
