### ISSUE TITLE
Disabling Dynamic Folding/Filters

### ISSUE THREAD

**Issue by dragonmaus** [chrisbra/csv.vim#162]
Is there a simple way to completely disable the dynamic folding/filtering functionality?

I frequently use \<Enter> and \<Space> to move the cursor, and whenever I am editing a CSV file this causes a fair amount of chaos.

**Comment by chrisbra** [comment]
Press `<BS>`?

**Comment by chrisbra** [comment]
I suggest to read the manual, after all, that's why it has been written :)

https://github.com/chrisbra/csv.vim#normal-mode-commands

closing.

**Comment by dragonmaus** [comment]
This does not solve the issue at all. The next time I hit <Enter> or <Space>, suddenly I will be in folded/filtered mode again.

I would like to disable the functionality completely.

**Comment by chrisbra** [comment]
Well, have you read the manual? What is not clear?

**Comment by dragonmaus** [comment]
While I admit that I have not taken the time to go through the entire manual word-by-word, I have searched through and carefully read everything related to folding or filtering. I'm not sure what you're hinting at here.

**Comment by chrisbra** [comment]
Follow the link I have given:

https://github.com/chrisbra/csv.vim#normal-mode-commands

At the end of the section it contains this snippet:

> 
> If you want to prevent the mapping of keys, simply set the global variable g:csv_nomap_<key> to 1, e.g. to prevent mapping of <CR> in csv files, put
> 
> let g:csv_nomap_cr = 1
> 
> into your .vimrc. Note, the keyname must be lower case.

So how about you try this?

**Comment by dragonmaus** [comment]
```vim
let g:csv_nomap_bs = 1
let g:csv_nomap_cr = 1
let g:csv_nomap_space = 1
```

That does seem to have done exactly what I was looking for, thank you.

----

(I apologize if my tone was drifting towards aggression; I was responding to an [erroneous] assumption that I was being brushed off.)

**Comment by chrisbra** [comment]
great, no problem.

**Comment by ledohod** [comment]
I have a similar problem, I can disable the keys but I want to keep the functionality of CR and Space. I don't see what command should I map alternative keys to. I would put <localleader><cr> for <cr>.

**Comment by chrisbra** [comment]
Don't understand.

**Comment by chrisbra** [comment]
put your custom mappings into a file called `~/.vim/after/ftplugin/csv.vim`

**Comment by ledohod** [comment]
Sorry, I meant something like this `nnoremap <leader>tn :tabnew <CR>`, where I wasn't sure what the `tabnew` equivalent would be for your `<space>` command. Are you saying if I put `nnoremap <localleader><cr> <cr>` in `~/.vim/after/ftplugin/csv.vim` it will work without specifying the function/command name?
