### ISSUE TITLE
CSV Syntax error on conditional load.

### ISSUE THREAD

**Issue by alpayne** [chrisbra/csv.vim#163]
The _CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)_ error also comes up if using plug.vim with a conditional load statement, regardless of the order of the `filetype ...` and `syntax on` lines.
```
Plug 'https://github.com/chrisbra/csv.vim',  { 'for' : 'csv' }
```
Removing the `{ 'for' : 'csv' }` conditional fixes the issue:
```
Plug 'https://github.com/chrisbra/csv.vim'
```
This isn't really something to be fixed, but a note to add to the troubleshooting instructions.

**Comment by chrisbra** [comment]
Thanks for noticing. I added something to the documentation.
