### ISSUE TITLE
Can't disable individual C-Left and C-Right mappings

### ISSUE THREAD

**Issue by jsatt** [chrisbra/csv.vim#165]
The way the map disabling configurations work you are unable to disable the C-Left and C-Right mappings using `g:csv_nomap_<key>`. This block, https://github.com/chrisbra/csv.vim/blob/7aa17f00a6cc96b9c9c364c6786c24f97c04605b/csv.vmb#L2284-L2286, is not handling the `-` in the map name, resulting in it checking for `g:csv_nomap_c-left` which is not a valid variable name.

Could we get some handling for this code to handle the `-` replacing it with `_` allowing for `g:csv_nomap_c_left` to be checked instead?

**Comment by chrisbra** [comment]
thanks, yes that was an overlook on my side. I'll fix it

**Comment by jsatt** [comment]
@chrisbra, Looks like that didn't quite do it. 
https://github.com/chrisbra/csv.vim/commit/61144a3955eb84dfdbd5b9acf17d78263bad7d04#diff-0d97eac82b617b6d0a25a831a4304335R2348

let keyname = substitute(**keyname**, '-', '_', 'g') instead?

**Comment by chrisbra** [comment]
of course. Sorry, I shouldn't do too many things at the same time

**Comment by jsatt** [comment]
@chrisbra That's working great now. Thanks for the quick response.
