### ISSUE TITLE
incorrect calculate result of some function

### ISSUE THREAD

**Issue by Freed-Wu** [chrisbra/csv.vim#168]
test.csv
```
header
2.042
2.040
2.040
2.043
2.042
2.043
2.039
2.030
2.040
2.043
2.042
2.041
2.039
2.039
```

```{.vim}
SmplStdCol
```

it will return 0.0

it is incorrect.

Thanks!

**Comment by chrisbra** [comment]
I suppose this is fixed by #169?

**Comment by Freed-Wu** [comment]
i doubt that there exists other problem...
test.csv
```
1
2
3
```

```{.vim}
SmplVarCol
```

the result is 1.00, it is  right.

![image](https://user-images.githubusercontent.com/32936898/84720307-4da53900-afb0-11ea-841e-d1b327ed1171.png)

but
```{.csv}
10
20
30
```

the result should be 100.00, because the number times 10, the variance must times 100. like this.

![image](https://user-images.githubusercontent.com/32936898/84720403-8ba25d00-afb0-11ea-8415-b1a585b3ad40.png)

```{.vim}
SmplVarCol
```

however, the result is 50.00.

if use

```{.csv}
0.1
0.2
0.3
```

it will also return an incorrect answer 0.13.

![image](https://user-images.githubusercontent.com/32936898/84720692-53e7e500-afb1-11ea-86a7-455d169277d8.png)

i thought it is because accuracy, but now i doubt the function to calculate variance perhaps is not 100% correct.

**Comment by chrisbra** [comment]
Hm, I personally do not use the standard deviation and this has been contributed. Perhaps there is a problem, yes.

**Comment by chrisbra** [comment]
can you please check again?

**Comment by chrisbra** [comment]
Make sure to disable headerlines, if you do not use one:

`let b:csv_headerline=0`

**Comment by Freed-Wu** [comment]
```
let b:csv_headerline=0
```

when test1.csv is
```
10
20
30
```

```
SmplVarCol
```

its result is 100. now it is right.

when test2.csv is
```
0.1
0.2
0.3
```

the result is 0.07, it should be 0.01.

Although i can use the result of test1.csv to calculate 100/10000=0.01, but if it can return a correct result correctly, it will be better:)

**Comment by chrisbra** [comment]
> when test2.csv is
> 
> 0.1
> 0.2
> 0.3
> 
> the result is 0.07, it should be 0.01.

This does print for me 0.01

**Comment by Freed-Wu** [comment]
I forget to update. Sorry:(
