### ISSUE TITLE
Plugin doesn't load other file extension

### ISSUE THREAD

**Issue by aganm** [chrisbra/csv.vim#176]
I followed the manual installation instruction.

In my .vim/filetype.vim, I put
```
if exists("did_load_csvfiletype")
  finish
endif
let did_load_csvfiletype=1

augroup filetypedetect
  au! BufRead,BufNewFile *.csv,*.xsv	setfiletype csv
augroup END
```

When I open .csv files, the plugin works fine. When I open a .xsv, I have this error 
```
CSV Syntax: Invalid column pattern, using default pattern \%([^,]*,\|$\)
``` 
and it doesn't work.

I read other issues, one was saying to source csv.vmb but that didn't help. Any idea how I can fix this?

**Comment by chrisbra** [comment]
If you see that error message, it indicates the plugin has actually been sourced.

**Comment by chrisbra** [comment]
so why do you think it doesn't work?

**Comment by aganm** [comment]
Because when I open a .csv file, it looks like this
![image](https://user-images.githubusercontent.com/20380758/96347088-47fa5580-106d-11eb-9072-f413f7f8228f.png)

If I type :CS then press <C-d> to autocomplete, I can see the CSV functions
![image](https://user-images.githubusercontent.com/20380758/96347120-737d4000-106d-11eb-8457-b2bd7e735a1f.png)

Now when I open the same file changed to .xsv, it looks this this
![image](https://user-images.githubusercontent.com/20380758/96347140-93acff00-106d-11eb-814c-38bb92f4189c.png)

And if I type :CS then press <C-d>, that's all I have
![image](https://user-images.githubusercontent.com/20380758/96347151-a6bfcf00-106d-11eb-8add-d8df2350aa5e.png)

**Comment by chrisbra** [comment]
okay, that makes sense. What does `:verbose set ft?` give you then?

**Comment by aganm** [comment]
hmmm, it gives me `filetype=`

**Comment by chrisbra** [comment]
Can you change that: 

      au! BufRead,BufNewFile *.csv,*.xsv	setfiletype csv

to

       au! BufRead,BufNewFile *.csv,*.xsv	set filetype=csv

does that work then?

**Comment by aganm** [comment]
Thanks, I finally got it working. I had to change two things.

First the line you told me to change
`   au! BufRead,BufNewFile *.csv,*.xsv	set filetype=csv`

And I had these 2 lines in my vimrc which would break the xsv file support
`filetype indent plugin on`
`syntax on`
I just had to move them after loading your csv plugin instead of before and then it worked.

Thanks for your help
