### ISSUE TITLE
Problems with large tab-separated data file

### ISSUE THREAD

**Issue by ruffson** [chrisbra/csv.vim#178]
First of all thank you for this awesome plugin! Unfortunately I cannot use it with tsv files.
I am dealing with a 55MB large [tab separated file](https://astropedia.astrogeology.usgs.gov/download/Mars/Research/Craters/RobbinsCraterDatabase_20120821.zip) with over 300k rows. (the data is zipped again as `RobbinsCraters_tab.txt.gz` inside the ZIP if you wanna have a look). I renamed the ending to `tsv` and added that to the `filename.vim` so it automatically recognizes it. 

However when I open the file with `neovim` 0.4.4 it only shows the header column, no data at all. And furthermore any action I do is extremely slow. It takes **one minute** to move right after pressing `l` once.
I tried loading a copy of that file with only the first 5 rows. That worked really well, it detects the tab as separator and everything is fine.

So I looked  at the other discussion over [here](https://github.com/chrisbra/csv.vim/issues/42) and it seems that the files others can deal with are even larger than mine. So I wanted to know if there is any optimization I can turn on, like only loading chunk-wise into the buffer at a time.
My hardware is pretty ok with an AMD Ryzen 7 4800H, Evo Plus SSD and 32GB of RAM. (My [init](https://github.com/ruffson/dotfiles/blob/master/init.vim) if it helps)

Any advise would be much appreciated!

**Comment by reportaman** [comment]
@ruffson I think there is a fundamental problem with Vimscript based implementation. I experience extreme slowness even for a file that has 1461 rows, and 81 columns, check this .csv example (renamed as .txt to be able to upload here): [train.txt](https://github.com/chrisbra/csv.vim/files/6096477/train.txt)

A way better solution is to use https://github.com/andmarti1424/sc-im, it has Vim bindings & a lua API too. The project is looking for more funding, and interest though. Please do consider donating if you find it useful, I am.

**Comment by ruffson** [comment]
Thank you @reportaman I'll have a look!

**Comment by ruffson** [comment]
I don't know what happened in the meantime here or if something changed with a recent neovim build but I can now open large files reasonably well. So closing this.
