### ISSUE TITLE
Errors for ConvertData on empty cells

### ISSUE THREAD

**Issue by poetaman** [chrisbra/csv.vim#180]
I ran ``:ConvertData!`` on a simple contacts.csv file that has 3 columns: Firsname, Lastname, email. Pre/Post values are empty, and the main conversion string is simple: ``<%s %s> %s``. I get following errors, which I suspect are because some contacts do not have any value in 3rd column. **Update The first two errors (E121,E116) still occur even if I have no empty cells.** Git blame shows the function ``csv#DoForEachColumn`` was last changed in mid-2018, baffled that no one used this nifty facility ``:ConvertData`` for so long... or something is deeply broken in my setup.

Expected: No errors, and don't print anything for cells that are empty (currently it prints ``%s``)

```
Error detected while processing function csv#PrepareDoForEachColumn[7]..csv#DoForEachColumn:
line   22:
E121: Undefined variable: line
E116: Invalid arguments for function foldlevel(line)
line   55:
E684: list index out of range: 2
E116: Invalid arguments for function substitute(t, '%s', fields[j-1], '')
E684: list index out of range: 2
E116: Invalid arguments for function substitute(t, '%s', fields[j-1], '')
E684: list index out of range: 2
E116: Invalid arguments for function substitute(t, '%s', fields[j-1], '')
E684: list index out of range: 2
E116: Invalid arguments for function substitute(t, '%s', fields[j-1], '')
```

**contacts.csv**
```csv
First;Last;Primary Email
Alex;Alex;alexalex@msn.com
Alex;Bram;
Bram;Moolenar;
Sir;Alex;siralex@gmail.com
Adriel;Zimmer;
Maddy;Daddy;maddy@gmail.com
Erica;Acire;
Panhan;Jiabao;pajiabao@yahoo.com
```

**result**:
```
First Last> Primary Email
<Alex Alex> alexalex@msn.com
<Alex Bram> %s
<Bram Moolenar> %s
<Sir Alex> siralex@gmail.com
<Adriel Zimmer> %s
<Maddy Daddy> maddy@gmail.com
<Erica Acire> %s
<Panhan Jiabao> pajiabao@yahoo.com
```

**Comment by chrisbra** [comment]
fixed by 56d1aa58a96b1b9394b80bfd5a001b221104d6da
