### ISSUE TITLE
Sort is not working

### ISSUE THREAD

**Issue by hsvdg** [chrisbra/csv.vim#192]
Sorting on a collumn does not seem to work. Even when using with the "n" modified, number seem to get sorted by their length first, only then by the numerical value.

**Comment by chrisbra** [comment]
I cannot reproduce this

**Comment by hsvdg** [comment]
Here is a small .csv. I sorted it using 
2,$ Sort 3

[tmp.csv](https://github.com/chrisbra/csv.vim/files/6398904/tmp.csv)

**Comment by chrisbra** [comment]
so you want sorting on floats. Should be possible now using `:2,$Sort 3f`

**Comment by hsvdg** [comment]
Thank you for the quick response (really quick). I was not aware that sorting on floats was not enabled. I updated the package, but I still get the wrong order on the data I uploaded.

**Comment by chrisbra** [comment]
It worked for me. Did you use the flag `f`?

**Comment by hsvdg** [comment]
Yes, I did use the f flag, as you indicated.
-I downloaded the latest version via vundle.

-My version of vim is: NVIM v0.4.3

Thank you for this...

BTW: With or without sorting, this is really great software. I use it all
the time!

Dominique

Am Do., 29. Apr. 2021 um 16:03 Uhr schrieb Christian Brabandt <
***@***.***>:

**Comment by chrisbra** [comment]
Not sure, but this is what it looks like for me using nvim 0.4.4:
![image](https://user-images.githubusercontent.com/244927/116655125-cde74980-a98a-11eb-8dd8-4e023a22e8af.png)

**Comment by hsvdg** [comment]
Hi,

thank you again for looking into this. I tried this out with vim (i.e.
not nvim) and it worked. 

On nvim still no luck (btw, I used the exact same .vimrc for both).

Let me know if you need some more information.

Dominique
