### ISSUE TITLE
[Bug] Error: using List as a String

### ISSUE THREAD

**Issue by BachoSeven** [chrisbra/csv.vim#194]
This seemed to have been introduced by https://github.com/chrisbra/csv.vim/commit/67e70f0949e6ea7a9d0a74fd3c3f96f75547798b#diff-cacdd5fb068ee249ac69074cc5be8dec023069cbb34443c09469bcdcfb938031R68.

![image](https://user-images.githubusercontent.com/55460785/117555941-f266b400-b063-11eb-8a81-40493b174f25.png)

**Comment by chrisbra** [comment]
Yeah, stupid me 🙈 

Should be fixed now.
