### ISSUE TITLE
Combining marks confuse ArrangeColumn

### ISSUE THREAD

**Issue by bpj** [chrisbra/csv.vim#195]
As mentioned in #174 I (ab)use this plugin to edit Markdown pipe tables. When doing so I have noticed that ArrangeColumn gets confused by combining marks. It's actually quite trivial: the width of the column is calculated from the number of characters so that (a) one character's worth of width is added also for the zero-width characters and (b) cells/rows containing zero-width characters get misaligned, though not always for some reason.

I just wonder if there might be some reasonably easy fix for this?

**Comment by chrisbra** [comment]
hm, can you provide an example please?

**Comment by bpj** [comment]
>
> hm, can you provide an example please?
>

I'm AFK today but I have an example on my phone (edited with Vim in
Termux.) It seems you can't do attachments in the mobile web interface so I
hope this email attachment works. Note the quite large amounts of extra
spaces in some columns. Done with left alignment and strict columns if that
matters (and b:delimiter='|' obviously!) Never mind the .tsv extension; I
tried .psv but my phone doesn't like that.

>

**Comment by bpj** [comment]
The email attachment didn't work. Let's see if a huge codeblock works. Sort of but the combining marks in the top row aren't displayed correctly on my phone. I hope they are still there.

``````
  |◌    |◌̣ |◌̤   |◌̱, ◌̄|◌̇   |◌̌   |◌̤̌      |◌̦ | |◌̦̌|◌̂  |◌̤̂ |◌̊          |◌̑             |◌̆             
c |k    |∅ |g   |x, h|    |tʃ  |dʒ     |s | | |ts |  |
ch|tʃ   |∅ |dʒ  |ʃ   |k   |tʃ  |dʒ     |  | | |   |
d |d    |∅ |t   |ð   |    |dʒ  |tʃ     |  | | |   |
f |f    |∅ |v   |    |    |    |       |  |
g |g    |∅ |k   |ɣ   |    |dʒ  |tʃ     |  | | |   |
gh|∅    |∅ |∅   |ɣ   |g   |dʒ  |tʃ     |  | | |   |  |f            
h |h    |∅ |ɦ   |x   |    |    |       |  | | |
j |dʒ   |∅ |tʃ  |ʒ   |    |dʒ  |tʃ     |  | | |dz |  |           |j             |x, h           
k |k    |∅ |g   |x, h|    |tʃ  |dʒ     |  | | |   |  |
l |l    |∅ |    |ɬ   |    |    |       |  | | |   |  |w          |ʎ, lj         |ɫ             
n |n    |∅ |    |    |    |    |       |  | | |   |  |           |ɲ               
ph|f    |∅ |v   |f   |p   |    |       |  | |
q |k    |∅ |g   |x, h|    |tʃ  |dʒ     |  | | |   |  |kw         |kj              
r |/r/  |∅ |r̥   |ɹ, ɻ|ɾ   |ʒ   |ʃ      |  | | |   |  |r          |              |             |ʁ, ʀ           
s |s    |∅ |z   |    |    |ʃ   |ʒ      |  |
t |t    |∅ |d   |θ   |    |tʃ  |dʒ     |s | |ʃ|ts |
th|ð    |∅ |θ   |d    
v |v    |∅ |f   |    |    |    |       |  | | |   |  |w           
x |ks   |∅ |gz  |x   |    |tʃ  |dʒ     |s |z|ʃ|   |dz|
y |j    |∅ |    |
z |z    |∅ |s   |    |    |ʒ   |ʃ      |  | | |dz |ts 
 ``````

**Comment by chrisbra** [comment]
this seems to work for me:
![image](https://user-images.githubusercontent.com/244927/123091234-64833480-d429-11eb-856a-77fc9727b136.png)
