### ISSUE TITLE
Columns do not line up.

### ISSUE THREAD

**Issue by allomorphy** [chrisbra/csv.vim#196]
Hi and thank you for this nice work,

I have tried everything that I could think of and find in the docs but cannot achieve Arrange (ment) of the columns

```                  
A│                               B│                              C│                              D│                          E│                                   F│                                 G│
Salutation│    Contact1 First Name│    Contact1 Last Name│    Contact1 Birthdate│    Contact1 Title│    Contact1 Personal Email│      Contact1 Work Email│    Contact1 Alternate Email│    Contact1 Preferred Email│    Contact1 Home Phone│
        Dr.│                  ZDxvzd│                ZOlzvzr│                       │                   │                            │     zdxvzdolzvzr1@nhs.nzt│                             │                         Work│
   ```
        
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/50141922/122559827-201a2200-d040-11eb-8d1a-09d883600d36.png">

I did the `CSVInit` followed by `ArrangeColumn`
Every time I type the latter command, then the top column moves one char space to the right.

Thanks for any tips to get it to behave as intended.

I used the Neobundle method on  NVIM v0.5.0-dev+1423-ge2d3ad7bc

Thank you and Best wishes
Eric

**Comment by chrisbra** [comment]
So the first line is the header? And you are actually using the `|` as delimiters? Have you tried `:%Arrange` so that it affects all lines?

**Comment by allomorphy** [comment]
Haleluljah! I should have mailed earlier.
(I am awaful at reading docs, I was jaded after trying a 2015 csv Plugin and I think that was by default global.)
The delimeters are  simply `,`

Just to save me misreading the docs again:
I noticed that  , then when I looked at the file again after using the plugin to `:%ArrangeColumn`, then it space padded the file and it changed.
So I imagine that the workflow is to `%UnArrangeColumn` before saving?

Thanks

**Comment by chrisbra** [comment]
yes, :%UnArrange should work. Not sure if it works by default on the whole file or not. So try with or without the `%`. (I don't remember since I do not work as much with CSV files as I used to, so unfortunately, this plugin hasn't actually gotten as much love as it should :/ )
