### ISSUE TITLE
invalid column pattern error

### ISSUE THREAD

**Issue by rudrab** [chrisbra/csv.vim#199]
Hi, while opening any `csv` file, I am getting error:
`Invalid column pattern`

![Screenshot from 2021-09-14 07-14-22](https://user-images.githubusercontent.com/4639447/133181165-5ea08c85-865a-4646-bbd3-33378a66defa.png)

I have installed the plugin using `vim-plug` and used:
```
" CSV: {{{2
if exists("did_load_csvfiletype")
  finish
endif
let did_load_csvfiletype=1

augroup filetypedetect
  au! BufRead,BufNewFile *.csv,*.dat  setfiletype csv
augroup END
" }}}2
```
no other csv related config is there in my` .vimrc`.
A sample csv  is also attached. 
[head.csv](https://github.com/chrisbra/csv.vim/files/7158358/head.csv)

This file when opened in vim  with ignoring the error is coming as 
![Screenshot from 2021-09-14 07-15-45](https://user-images.githubusercontent.com/4639447/133181538-0fdc64e2-7a57-4d3b-ac2d-1db6a92bdf07.png)

I would like to get rid of that error and want it to be properly columned.

**Comment by chrisbra** [comment]
check `:h csv-syntax-error`
