### ISSUE TITLE
invalid column separator/line generated for :CSVTabularize

### ISSUE THREAD

**Issue by etorth** [chrisbra/csv.vim#200]
see image:
![image](https://user-images.githubusercontent.com/1754214/135921873-cc28dfd1-c8e3-482e-ab8e-fcc9f9ae12f5.png)

this is a great plugin!

**Comment by etorth** [comment]
Let me also put the csv file here for your to debug:
[King_Magic.csv](https://github.com/chrisbra/csv.vim/files/7281197/King_Magic.csv)

**Comment by chrisbra** [comment]
hm, what vim version is this?

**Comment by chrisbra** [comment]
I cannot seem to reproduce

**Comment by chrisbra** [comment]
ah, hold on, I was using an older version. Let me investigate
