### ISSUE TITLE
Few seconds lag when moving between lines in large csv file

### ISSUE THREAD

**Issue by QuantumEspresso** [chrisbra/csv.vim#201]
When I load large csv file, moving between the lines (even up and down) takes a few good seconds.
The problem does not occur while moving in line.

My guess is that sticking to the column during movement is the issue.
Is there a way to speed it up without sacrificing sticking to the column?
If not how can I turn off this single feature?

**Comment by chrisbra** [comment]
Yes, quite likely. Try to use `j` instead of `J` (or cursor down) and `k` instead of `K` or cursor-up.

**Comment by QuantumEspresso** [comment]
Works like a charm :D

**Comment by QuantumEspresso** [comment]
Using j instead of arrow down worked like a charm :D
