### ISSUE TITLE
`:ArrangeColumn` corrupts date string?

### ISSUE THREAD

**Issue by gilbh** [chrisbra/csv.vim#205]
Hi,

Love your plugin!

When I open the following one-line csv file:
```
DOGEUSDT,buy,short,2021-11-04 08:00,0.2553,,,,[-59.75%],,,EMA_21=0.26914 EMA_50=0.26975 Vol_Osc=-55.88,
```
-- and then enter `:ArrangeColumn`, the forth column with the date string (`2021-11-04 08:00`) is truncated to: `2011`

Am I doing something wrong or is this a bug?

Thanks!

**Comment by chrisbra** [comment]
I cannot seem to replicate this
