### ISSUE TITLE
Aligning content of cell with line breaks

### ISSUE THREAD

**Issue by romanhaa** [chrisbra/csv.vim#210]
Hi,

I was wondering whether `csv.vim` can display rows with line breaks inside them one the same line? Maybe I just haven't figured out how to do it but I wasn't able to get them to display correctly.

See the following example:

```csv
col1,col2,col3
val1,"val2.1
val2.2","val3.1
val3.2"
```

![Screenshot 2022-07-18 at 15 01 30](https://user-images.githubusercontent.com/18103560/179516839-f3ee7197-4c35-4dac-8bfd-3055b2570645.png)

In Excel or whatever other GUI, this would probably be displayed as such:

![Screenshot 2022-07-18 at 14 59 25](https://user-images.githubusercontent.com/18103560/179516494-ddcc2727-e097-41e0-b789-2f07b40cae2f.png)

Is that possible somehow with `csv.vim`? The way it's displayed at the moment makes it really difficult to align the respective "sub-rows" in my mind. I suspect the answer is that I should fix the issue by splitting the content into multiple rows but it would be better for my workflow like this and I wanted to be sure that I'm not just missing a command or setting.

Thanks!

**Comment by chrisbra** [comment]
No this is not possible in vim

**Comment by romanhaa** [comment]
Ok, I thought so. Thanks for the response.
