### ISSUE TITLE
Auto Alignment Per Buffer

### ISSUE THREAD

**Issue by acamso** [chrisbra/csv.vim#211]
Hi, thanks for the great plugin. I am looking to set the alignment (`b:csv_arrange_align`) automatically for each individual buffer/file since the alignment needed varies. I was wondering if there's a recommended way to go about doing this. I found another plugin that allows setting variables in the modeline, but would rather not do that. Also, `dhruvasagar/vim-table-mode` allows a character to be added to statically set each column individually. Was wondering if that could be a possible enhancement.

Cheers

**Comment by chrisbra** [comment]
Not sure I understand, what exactly is the problem?

**Comment by acamso** [comment]
@chrisbra 

I have two files: `1.csv` `2.csv` - I need `let b:csv_arrange_align='l*'` for `1.csv` and `let b:csv_arrange_align='lc*'` for `2.csv` to be set automatically. I was wondering if there was a recommended way to handle alignment for each buffer.

**Comment by chrisbra** [comment]
can you not use `BufEnter` autocommands for that?

**Comment by acamso** [comment]
> can you not use `BufEnter` autocommands for that?

Yes can do that as well but could be a pain with alot of files. Turns out setting variables in the modeline is working great. 

Appreciate the plugin!
