### ISSUE TITLE
ArrangeColumn aligns not all lines

### ISSUE THREAD

**Issue by deniserdogan** [chrisbra/csv.vim#213]
When i try to arrange all columns by doing ` : ArrangeColumn ` it aligns just the line that my cursor is on but all lines.

<img width="1440" alt="Screenshot 2022-09-11 at 06 24 10" src="https://user-images.githubusercontent.com/40524858/189511041-ec6b4306-f305-447c-81e1-1713d83e4a9b.png">

**Comment by chrisbra** [comment]
yes correct. See also the documentation: 

https://github.com/chrisbra/csv.vim/blob/master/doc/ft-csv.txt#L219-L244

> If [range] is not given, it defaults to the current line.
