### ISSUE TITLE
csv#MoveCol resets vartabstop

### ISSUE THREAD

**Issue by outtersg** [chrisbra/csv.vim#218]
First hit on an arrow-up/down key (or J or K) on a freshly opened file (that autoaligned columns by defaut),
**breaks the autoalign** (by resetting vartabstop).

It seems related to #203 making `vts` local in `csv#CalculateColumnWidth`,
but removing (by error?) the "save it while temporary computing width of the new line",
at https://github.com/chrisbra/csv.vim/commit/25d9ab427443fea6edcd2217c76ca67aa80c3cd6#diff-cfdfb3845011b4e5afcb2544f2d6100548da8bb384206c246d2f9f0a0743156aL800-L802

**Comment by chrisbra** [comment]
fixed by #219
