### ISSUE TITLE
csv.vim pluging how to deactivate it (without uninstalling it)

### ISSUE THREAD

**Issue by LuisBL** [chrisbra/csv.vim#221]
https://stackoverflow.com/questions/75778112/csv-vim-pluging-how-to-deactivate-it-without-uninstalling-it

**Comment by chrisbra** [comment]
It's a filetype plugin, so simply set a different filetype: `:set filetype=text`

**Comment by bjce** [comment]
Thank you for this answer @chrisbra  , however with this solution I have to type `:set filetype=text` inside vim each time I open the csv. Is there a way to make the change permanent by modifying the `.vimrc` (until decided otherwise e.g. to switch back to the csv display type).

**Comment by bjce** [comment]
Ok: adding the following line in `vimrc` AFTER the plugin call commands solve the problem: `autocmd BufRead,BufNewFile *.csv set filetype=text " comment this line to read .csv file with the csv.vim commnet, uncomment the line to read .csv file as plain text`
