### ISSUE TITLE
Question: Pasting data into a column

### ISSUE THREAD

**Issue by openjck** [chrisbra/csv.vim#225]
Please let me know if there's a better place to ask questions.

Is there a way to paste data into a column? For example, imagine my clipboard contains 100 lines of text, separated by newlines. Is there a way to paste that data into a particular column, such that each line of text in the clipboard becomes one cell in that column?

This can be done in Excel. For example, if I copy the following data:

```
Kiley


Rosalia


Zondra
Samara
```

...then create a new Excel spreadsheet, left-click on cell A:1, and finally use `CTRL`+`V` to paste, the following results:

![A screenshot of Excel, with the data above occupying cells A:1 through A:8, in order, with empty spaces preserved](https://github.com/chrisbra/csv.vim/assets/933396/cda23076-20af-490d-a42f-094c5e19d385)

It's easy enough to do this when the spreadsheet is empty, but Excel also makes it possible to do this in any arbitrary column.

Can something like that be achieved using csv.vim?

**Comment by chrisbra** [comment]
It may be possible, by setting the register to be pasted to blockwise mode.

So try the following:
```
call setreg('a', '+', 'b')
norm! "ap
```

untested
