### ISSUE TITLE
HiColumn is leaky

### ISSUE THREAD

**Issue by harriott** [chrisbra/csv.vim#226]
`HiColumn` leaves trailing highlighting on other buffers.

Seems to be something to do with `csv#HiCol` in [csv.vim/autoload/csv.vim](https://github.com/chrisbra/csv.vim/blob/master/autoload/csv.vim).

Tested in a stripped down `Vim` configuration with only this plugin.

In another affected buffer, these don't clear the errant highlighting: `:colo default`, `:2mat none`. The only thing I can do is return to the buffer of the csv file and either `:HiColumn!` or `:CSVInit`, then return to the buffer of the other filetype.

**Comment by chrisbra** [comment]
what do you mean with `leaky`? I don't think the csv plugin uses highlight matches, but perhaps this is just `hls` highlighting that persists? Does `:nohls` fix it` Can you show a screen shot?

**Comment by harriott** [comment]
`:nohls` was such an obvious first thing to try I'd forgotten to mention that it also doesn't remove the leaked highlighting.

I ran again my stripped down vim configuration to grab some screen shots and noticed that the highlighting from `:HiColumn` even leaks into `Netrw` - [image here](https://www.dropbox.com/scl/fi/5o0ix4900vfjr18t2xxr9/effectOnNetrw.jpg?rlkey=13y6xsi5jqy5mm4b81hw4q0ej&dl=0).

**Comment by chrisbra** [comment]
hm, you seem to be changing the buffer in the window and the `:HiColumn` hightlighting isn't cleared then. Does `:call clearmatches()` does fix it?

**Comment by harriott** [comment]
Yes, I see that the leak is limited to the window that `:HiColumn` was called from.

In my workflows I often switch buffers within a window so now I've implemented in my vimrc:

    inoremap <s-f7> :call clearmatches()<cr>
    nnoremap <s-f7> :call clearmatches()<cr>

- which allows me to clear the leaked highlighting from any other affected buffer.

**Comment by chrisbra** [comment]
that is actually puzzling, because `:HiColumn` highlighting should be removed, once you change editing another buffer in the current window:

https://github.com/chrisbra/csv.vim/blob/15ff93edf5b26c466affbb356e0696b7d6a3b499/autoload/csv.vim#L230-L257

So can you check when your csv buffer is loaded, that there exists a corresponding autocommand?

```
:au BufWinLeave
```

For me it certainly clears the highlighting when switching to another buffer.

Please provide a reproducible example how this happens? Also please specify what version you are using

**Comment by chrisbra** [comment]
I have made some changes in ba2c5ff please verify

**Comment by harriott** [comment]
In my `$vimfiles/pack/packs-cp/opt/csv.vim`,
```Bash
$ git rev-parse --short HEAD
15ff93e
```

Just re-tested like this:
1) I made a directory `~/.vimtest` and from in there `mkdir -p pack/packs-cp/opt` into which I cloned `csv.vim`
2) I created a `vimrc.vim` containing these statements:
```vimscript
set runtimepath=~/.vimtest,/usr/share/vim/vimfiles,/usr/share/vim/vim90,/usr/share/vim/vimfiles/after
source $VIMRUNTIME/defaults.vim
packadd csv.vim
```
3) and I created `test.csv` containing these two lines:
```csv
header1,header2,header3
data1,data2,data3
```
4) still in directory `~/.vimtest`, `vim -u ~/.vimtest/vimrc.vim test.csv`
5) in that testing version of `Vim`, I `:HiColumn`, which works, then `e .` to open `Netrw` showing the leaked highlighting.

\- could there be something in `$VIMRUNTIME/defaults.vim` that conflicts with your plugin?

**Comment by chrisbra** [comment]
Well, can you please update to https://github.com/chrisbra/csv.vim/commit/ba2c5ff709dc0eb4fb6bb9433137e1329a329a59 and can you show the 
```
:au BufWinLeave
```
when in a csv file? 

Oh wait a second, you don't have a automatic highlighting setup? That might be the reason then.

**Comment by harriott** [comment]
Updated to 4fd8834, thanks.

`:Bufferize au BufWinLeave` gets me (relevant stuff):
```
--- Autocommands ---
...
CSV_HI2  BufWinLeave
    <buffer=2>
              sil! HiColumn!
              call csv#RemoveAutoHighlight()
              call csv#RemoveAutoHighlight()
...
CSV_HI2  BufWinLeave
    <buffer=2>
              call csv#RemoveAutoHighlight()
```
With your updated code I'm getting no more leaking of highlighting to other buffers, thanks.

A couple of points:

- It'd be nice if when we return to the `*.csv` the column highlighting was still there.
- Highlight column automatically (`let g:csv_highlight_column = 'y'`)
    - I've not been using because, with my choice of colorscheme ,[vim-colors-tomorrow](https://github.com/svermeulen/vim-colors-tomorrow), your column highlighting makes the cursor invisible. (This isn't an issue with [jellybeans.vim](https://github.com/nanotech/jellybeans.vim) colorscheme, which I prefer in `nvim` within my `tmux`.)
    - The column highlighting is lost when the buffer in the window has been changed.

**Comment by chrisbra** [comment]
you know, you can define your own highlighting.
