### ISSUE TITLE
Error on loading a file

### ISSUE THREAD

**Issue by thirstyice** [chrisbra/csv.vim#228]
The plugin isn't working for me
I get an error when loading a csv file:
<img width="1153" alt="Screenshot 2024-01-04 at 23 07 36" src="https://github.com/chrisbra/csv.vim/assets/5591891/81f6a915-018e-4395-97c9-33a1342fc7af">
(I know text would be better than a screenshot, but it wouldn't let me select it to copy-paste)

NVIM v0.9.5
Plugin installed with vim-plug
No other plugins installed

edit:
MacOS Sonoma 14.2.1

**Comment by thirstyice** [comment]
Looks like this is a problem with my Neovim, not with this plugin

**Comment by chrisbra** [comment]
Check your nvim, it seems you cannot execute the following command:
```
:sil lang mess C
```
