### ISSUE TITLE
[BUG] Default delimiter is not set as tab for .tsv files

### ISSUE THREAD

**Issue by letuanhai** [chrisbra/csv.vim#229]
When I open a .tsv file, `b:delimiter` is still set to `','` even after commit ee5c2aeba44155ae2058956fe261fb0fa2f4636c. If I `:let g:csv_delim='\t'` manually then run `:CSVInit` then the delimiter is set correctly.

So far I've found that adding a third parameter `1` to the `csv#Init` call in `ftplugin/csv.vim` fix the issue as it keeps the value `b:delimiter` set before `set filetype=csv`. And manually setting `g:csv_delim` to another value after filetype change would still work, though I'm not sure how it would affect other behaviours.
```diff
diff --git a/ftplugin/csv.vim b/ftplugin/csv.vim
index 03e6721..9538298 100644
--- a/ftplugin/csv.vim
+++ b/ftplugin/csv.vim
@@ -26,7 +26,7 @@ let b:csv_start = get(g:, 'csv_start', 1)
 let b:csv_end   = get(g:, 'csv_end', line('$'))
 let b:csv_result = ''
 
-call csv#Init(b:csv_start, b:csv_end)
+call csv#Init(b:csv_start, b:csv_end, 1)
 let &cpo = s:cpo_save
 unlet s:cpo_save
 
```

**Comment by chrisbra** [comment]
Hm, it should happen automatically: https://github.com/chrisbra/csv.vim/blob/962f88787ec6873eba1c7dbbd81d2723f1ee3c4b/ftdetect/csv.vim#L2

**Comment by letuanhai** [comment]
Yes, `b:delimiter` is set for the new buffer before the `filetype` is set but then after that the call to `csv#Init` here:
https://github.com/chrisbra/csv.vim/blob/962f88787ec6873eba1c7dbbd81d2723f1ee3c4b/ftplugin/csv.vim#L29C1-L29C38

because the parameter `a:1` for this function call is not set, it does not keep `b:delimiter`:
https://github.com/chrisbra/csv.vim/blob/962f88787ec6873eba1c7dbbd81d2723f1ee3c4b/autoload/csv.vim#L39-L41

**Comment by letuanhai** [comment]
After a bit more testing the problem only occurs with certain data files. I'll close this issue now and dig a bit more if this keeps coming up.
Thank you for your attention and I'm really sorry for taking your time.
