### ISSUE TITLE
AddColumn not working

### ISSUE THREAD

**Issue by CowKeyMan** [chrisbra/csv.vim#232]
Whenever I try to use the AddColumn function, no matter the parameter I give it, I get this error (using neovim)

```
Error detected while processing function csv#AddColumn:
line   54:
E121: Undefined variable: commentpat
E116: Invalid arguments for function empty
Press ENTER or type command to continue
```

Any idea what is going on here?

**Comment by chrisbra** [comment]
not sure, can you please update and try again? Not sure why `commentpat` would not be initialized for you

**Comment by CowKeyMan** [comment]
That was super quick! It works now, thank you!
