### ISSUE TITLE
Please add license to repo

### ISSUE THREAD

**Issue by dkontyko** [chrisbra/csv.vim#233]
This is a smaller request, but can you please add a license to this repo? I realize it may not be a consideration for most users, but it can be helpful for companies that have stricter open source requirements. (I would've created a PR for this, but I don't want to assume your licensing preference.)

I would recommend the MIT license, but the choice is ultimately yours. :)

Thanks!

**Comment by chrisbra** [comment]
https://github.com/chrisbra/csv.vim/blob/85e6a9f24b68f213b5423a0840f2dc9831eb3edb/doc/ft-csv.txt#L7-L8

**Comment by chrisbra** [comment]
sorry, I didn't mean to close it.
