### ISSUE TITLE
Set delimiter

### ISSUE THREAD

**Issue by 945fc41467** [chrisbra/csv.vim#234]
I didn’t find how to specify the delimiter when wrongly detect. I tried `let b:delimiter=";"` and `let g:csv_delim=";"`. Nothing happen.

**Comment by chrisbra** [comment]
`:h NewDelimiter_CSV`

**Comment by chrisbra** [comment]
You know, it helps if you mention what you already tried.  See `:h CSVInit` and `:h csv-configuration`. 

>  But he syntax color doesn’t fall back to the , 

That's why you need to re-initialize the plugin using `:CSVInit`.
