### ISSUE TITLE
 CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\) Error Message

### ISSUE THREAD

**Issue by jbelmont** [chrisbra/csv.vim#29]
Hello:

I am using your plugin in conjunction with the MySQL Workbench on Mac OS X 10.7.
When I export my sql scripts from the MySQL Workbench I get the following error message:  CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,|$) 
but if I cat the contents of the file I see that there is commas as delimiters in the file. Is 
there something that I am doing wrong.

Sincerely,

Jean-Marcel Belmont

**Comment by wzyboy** [comment]
In case anyone is reading this -- as documented in `:h csv-syntax-error`:

```
Note: It could also be caused by lazy loading feature by a vim plugin
manager. For example this line might also cause it:                  
                                                                     
  Plug 'https://github.com/chrisbra/csv.vim',  { 'for' : 'csv' }     
                                                                     
                                                                     
The fix would then be:                                               
                                                                     
  Plug 'https://github.com/chrisbra/csv.vim'                         
```

So if you do not have `syntax on` before ftplugin, check whether your plugin manager has lazy/conditional loading and disable it for `csv` type.
