### ISSUE TITLE
Make ConverData align decimal points

### ISSUE THREAD

**Issue by DanielAndreasen** [chrisbra/csv.vim#34]
Hi,

Is it possible to use ConvertData to align decimal points?
I have a data file where the decimal points should be at a specific place.

I have tried to type something like this at the third question after ConvertData<CR>

%s        %s                 %s   %s   %s

(the raw line above shows different amount of spaces in between, but it is apparently processed and eaten by markdown).
So as you can see I have five columns.

Cheers,
Daniel

**Comment by chrisbra** [comment]
I think, this should be possible now. You need to :%ArrangeColumn first and specify the alignment using the g:csv_arrange_align variable. Then I think the ConvertData function should use the converted values.

**Comment by DanielAndreasen** [comment]
Thanks for including this. In the meantime I wrote a python script to do this. I think we can close this issue then?
