### ISSUE TITLE
Custom text group

### ISSUE THREAD

**Issue by justmytwospence** [chrisbra/csv.vim#44]
A cool feature idea occurred to me today. It would be neat if one could `vig` ("visual-in-group") to visually select a contiguous block of rows, where a block is defined as all the contiguous rows having the same value in the cursor's column. Obviously this would only work for sorted data. Yank, delete, etc would be handy with this text group too. Does this sound possible?

**Comment by chrisbra** [comment]
Sounds like a useful feature. I'll look into implementing this.

**Comment by chrisbra** [comment]
Try with the latest version. It implements the 'iL' text object (see :h csv-textobjects)

**Comment by justmytwospence** [comment]
Beautiful - thanks!
