### ISSUE TITLE
Custom CSVColumnEven highlight does not work

### ISSUE THREAD

**Issue by ptzz** [chrisbra/csv.vim#47]
the `hi CSVColumnEven term=NONE ctermbg=NONE` in my `.vimrc` seems to be overwritten when a csv file is loaded. It is set to my modified value when vim is started, but overwritten when I load a .csv file.

**Comment by ptzz** [comment]
Doing `au FileType csv hi CSVColumnEven term=NONE ctermbg=NONE` solves the problem. Is this by design? Or should `csv.vmb` have a check if `CSVColumnEven` is already set before setting it to the default value?

**Comment by chrisbra** [comment]
Thanks for the feedback.
Looks like hi def link will overwrite even though it shouldn't in my opinion. I have pushed a fix, can you test it?

**Comment by ptzz** [comment]
Works like a charm, thx! :+1:
