### ISSUE TITLE
Display-only live column arrangement?

### ISSUE THREAD

**Issue by naught101** [chrisbra/csv.vim#48]
It would be nice to have a view mode that is like the results of :ArrangeColumns, but doesn't actually modify the file. That is, column widths are calculated, and then the separator is displayed as `<sep><x spaces>` where x is `column width - column contents width`. Ideally, column widths would be corrected whenever a cell was edited (not while in insert mode, but after).

I'm not sure how feasible this would be, given Vim's structure, nor how computationally intensive this would be, but it would be really nice for smallish CSVs anyway.

**Comment by chrisbra** [comment]
I think, this is like the collapse feature from issue #41 . This might be possible, with the conceal feature, but probably makes Vim a lot slower.

**Comment by chrisbra** [comment]
closing see #41

**Comment by naught101** [comment]
Yeah, fair enough, I didn't realise that that was discussing a view-only arrangement. The ability to have that work on non-arranged columns would be an extra.
