### ISSUE TITLE
dynamic filter and count

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#49]
Hello,

Thank you for creating the wonderful vim plugin!

I have a column dynamically filtered and I'd like to count all instances that are now present with the filter. How can I do this? Skipping to the end of the file shows the last line number and all the folds but not a correct count. 

Thanks,
jungle

**Comment by chrisbra** [comment]
Well, you could write a custom aggregate function, that counts the values. But for convenience I have included a :CSVCount command, that counts all values within a column (not respecting the header line and folded lines). Use the optional distinct parameter to count only distinct values.

**Comment by jungle-boogie** [comment]
Thanks, works wonderfully.
