### ISSUE TITLE
Prevents visualmode from selecting over multiple lines with arrow keys.

### ISSUE THREAD

**Issue by naught101** [chrisbra/csv.vim#50]
If csv.vim is enabled, I can't use `v`, `<s-v>` or  `<c-v>` to select over multiple lines with the arrow keys. It still works with `hjkl`, but I don't really use these keys, so it is really annoying. Not sure if this is something to do with some other plugin or something.. Let me know if there is some more info I can provide.

**Comment by chrisbra** [comment]
Thanks for noticing me. Should be fixed now.

**Comment by naught101** [comment]
Great, works perfectly, thanks!
