### ISSUE TITLE
ArrangeColumn increase column width every time.

### ISSUE THREAD

**Issue by naught101** [chrisbra/csv.vim#51]
If I open a small CSV file, and `:%ArrangeColumn`, then the columns are arranged, with whitespace equal to the minimum +1. If I repeat  `:%ArrangeColumn`, then the same thing happens, and now there is at least 2 spaces at the start of every column. Every time this is repeated, one more column of whitespace is added.

The preferred behaviour for me would be that every column has at most one column of pure whitespace  after a separator. So if a CSV is already arranged, `:%ArrangeColumn` should do nothing, and if somehow a column already has more than 1 space before each cell (e.g. if some text was edited), then all but one of those spaces should be removed.

**Comment by chrisbra** [comment]
Thanks for noticing. Should be fixed now.

**Comment by naught101** [comment]
Beautiful, thank you :)
