### ISSUE TITLE
CSVAnalyze giving funky results

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#52]
So I'm doing CSVAnalyze on 65,867 records and it works pretty fast but the results are quite strange. My numbers are dollar amounts and some don't have a decimal. 

I don't know markdown well enough to make the table look decent so it's here:
https://github.com/jungle-boogie/photographs/blob/master/results

As you see, four of the 5 results have 0% and interestingly the 1% result appears 8 times in the file.

Here's the data I used:
https://github.com/jungle-boogie/photographs/blob/master/data

Are these results expected?

Thanks,
jb

**Comment by chrisbra** [comment]
Oh there was something broken. Should be fixed now.

**Comment by jungle-boogie** [comment]
Thanks!

Looks much better: https://gist.github.com/jungle-boogie/7e4127ac9906eb50f389

7% of those transactions are only $7!

**Comment by chrisbra** [comment]
Hi jungle-boogie!

On Do, 11 Jun 2015, jungle-boogie wrote:

> Thanks!

Your welcome.

> 
> Looks much better: https://gist.github.com/jungle-boogie/7e4127ac9906eb50f389
> 
> 7% of those transactions are only $7!

Is that good or bad?

Best,
Christian
-- 
Für seinen Hund ist jeder Mensch Napoleon. Darum sind Hunde so
beliebt.
		-- Aldous Huxley

**Comment by jungle-boogie** [comment]
>>  7% of those transactions are only $7!

> Is that good or bad?

Just surprising but I suspect it's accurate. What's a grep command to find exactly and only 7, not 7.*?

**Comment by chrisbra** [comment]
Hi jungle-boogie!

On Do, 11 Jun 2015, jungle-boogie wrote:

> Just surprising but I suspect it's accurate. What's a grep command to
> find exactly and only 7, not 7.*?
for that  data? 

grep '[,]7$' data.csv


Best,
Christian
-- 
Wir sind Diplomaten. Das heißt: Wenn wir sagen, was wir denken, haben
wir uns versprochen.
		-- Henry Morton Robinson (Der Kardinal)

**Comment by jungle-boogie** [comment]
Hi Chrisbra,

> for that  data?
grep '[,]7$' data.csv

Matches so your fix is great! 

Thanks for a quick resolution.

Best,
jungle
