### ISSUE TITLE
ConvertData ignoring dynamic filters

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#53]
Hello,

Is it the intention of the csv.vim plugin's CSVConvert option to ignore dynamically filtered data and convert an entire file when you only wanted a subsection?

My 12 MB file (116877 lines) turned into a 22MB html file after I wanted to convert only 6 rows and 8 columns. 

Thanks!

**Comment by chrisbra** [comment]
No, need to change this
