### ISSUE TITLE
Save dynamic filter results to separate file

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#54]
Hello,

Is there a vim way or a method with this plugin to save dynamically filtered results to a separate file? 

After filtering a file, I have just 1,115 records showing but many, many folds visible so I attempt to do :w file.csv, it writes the file and I do a `wc -l` to find out I just duplicated the original file with 116877 lines.

**Comment by chrisbra** [comment]
I think, you can do this:
    :folddooopen :w >> fileout.txt

**Comment by jungle-boogie** [comment]
> I think, you can do this:
`:folddooopen :w >> fileout.txt`

I'll look this up more but I tried :folddoopen :w >> file.csv and ended up with a 37,785,152 line file  at 4.2GB unless the problem is you can't redirect to a file in the same directory as your original file.

**Comment by chrisbra** [comment]
Yeah this was wrong. Without a line range, `:w` always writes the complete buffer. So you must specify a range to the `:w` command. This should work:
     `:folddoopen .:w >> fileout.txt

**Comment by jungle-boogie** [comment]
> `:folddoopen .:w >> fileout.txt`

That works great but I have to `touch fileout.txt` because you're appending it and 
`:folddoopen .:w > fileout.txt` just writes the header over and over--no visible data from the non-folded data is saved:
"fileout.txt" 1L, 86C written


This just may be a vim thing, though.

**Comment by jungle-boogie** [comment]
This is it:
`:folddoopen .:w! >> file`

Use ! even if the files doesn't exist.
