### ISSUE TITLE
Dynamic filters & excluding

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#55]
Hello,

Gist example here:
https://gist.github.com/jungle-boogie/34d9eea4002551428b55

Not the best but it will work.

Say I want to filter on the 5th column (type) and I then get 21 results with the majority of chrisbra at 57%.

Can chrisbra be excluded from the results?

Thanks,
jb

**Comment by jungle-boogie** [comment]
Hi Chrisbra,

I think you can already do this with the space to exclude and enter to include.

If you take my data, you go to the 5th column and press enter and then go to second column to and press space bar. 

Updated gist: 
https://gist.github.com/jungle-boogie/34d9eea4002551428b55

Is this correct?

**Comment by chrisbra** [comment]
Yes, that is correct.
