### ISSUE TITLE
CSVTabularize not respecting dynamic filters

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#56]
Hello,

Is it the intention of the csv.vim plugin's CSVTabularize option to ignore dynamically filtered data and put all results in a table?

Thanks,
jungle

**Comment by chrisbra** [comment]
Will make it aware of the filter, so those will be excluded
Thanks for noticing.

**Comment by chrisbra** [comment]
should be fixed now.

**Comment by jungle-boogie** [comment]
Hello Chrisbra,

It doesn't look like this is corrected.  In fact, after filtering data out and running :CSVTabularize, the vim session hangs and it has to be manually killed. 

Thanks,
jungle

**Comment by chrisbra** [comment]
Yes, ther ewas an off by one error. And it didn't work correctly anyhow. I changed so that the table will open ín a new window. Please check.

**Comment by jungle-boogie** [comment]
Works as expected, thanks!
