### ISSUE TITLE
dynamic filter ignoring decimal point

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#57]
Hello,

While I was reviewing a CSV file to find the most common number, I used the dynamic filter to show all 20 values but I noticed 20.** would also appear in the results.

Here is a gist with an explanation:
https://gist.github.com/jungle-boogie/53562fe9e105eaaf4e69

Thanks,
j

**Comment by chrisbra** [comment]
should be fixed now.
