### ISSUE TITLE
set csv-delimiter man page

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#58]
Hello,

When you open a file that csv.vim doesn't not recognize with a valid header, you're advised:
`CSV: No delimiter found. See :h csv-delimiter to set it manually!;` however, vim complains this help page does not exist.

4.1 of the manual csv.vim manual indicates to use this to set delimiter:
`:let g:csv_delim=','`

When attempting to set the less common ':' as the delimiter, there is no error message but csv.vim doesn't seem to respect this delimiter, and you can test this by typing some data separated by : and then using the dynamic filter to see filter doesn't  work.

**Comment by chrisbra** [comment]
Have you tried reinit the plugin using `:InitCSV!`

**Comment by jungle-boogie** [comment]
Hello,

Yes, this worked.

You first need to set the delimiter and then reinitialize.

Upon opening a file without the recognized header, though, should the error message text change?

**Comment by chrisbra** [comment]
i do not understand. When should the error message change?

**Comment by jungle-boogie** [comment]
Hello,

>i do not understand. When should the error message change?

This message:
`CSV: No delimiter found. See :h csv-delimiter to set it manually!`

Because doing :h csv-delimiter doesn't actually bring up any page.

**Comment by chrisbra** [comment]
Am 2015-06-15 07:14, schrieb jungle-boogie:
> Hello,
> 
>> i do not understand. When should the error message change?
> 
> This message:
>  CSV: No delimiter found. See :h csv-delimiter to set it manually!
> 
> Because doing :h csv-delimiter doesn't actually bring up any page.
> 

Sorry, I can't reproduce it. The help page at section 4.1 delimiter
has the correct tag at the end:
4.1 Delimiter							*csv-delimiter*

And for me :h csv-delimiter works. Could you please check your help 
file?

Thanks.
