### ISSUE TITLE
CSVSort using lexical sorting 

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#59]
Hello,

Gist here with data: https://gist.github.com/jungle-boogie/f899acae799359f20711

Sorting is doing it like 900, 800, 8, 700 which results in four digit numbers being incorrectly sorted.

Thanks,
jungle

**Comment by jungle-boogie** [comment]
By the way, this will also affect values that contain decimal values.

96.21
9.95
8.75
8.65
8.05
8
77.52
70.75
7.85
7.70
7.20
7.10

**Comment by chrisbra** [comment]
That should alreadyy work, when you give the `:Sort` function the 'n' flag.

**Comment by jungle-boogie** [comment]
Hello,

>That should alreadyy work, when you give the :Sort function the 'n' flag.

Yes, this is correct! That's wonderful.

Thanks,
Jungle

**Comment by jungle-boogie** [comment]
I may have closed this a bit too soon, sorry.

If you take my small sample above and :Sort! n, the results:

96.21
77.52
70.75
9.95
8.75
8.65
8.05
8
7.85
7.70
7.20
7.10
numbers

If I make that 8 read 8.00, it will sort correctly:
96.21
77.52
70.75
9.95
8.75
8.65
8.05
8.00
7.85
7.70
7.20
7.10
numbers

**Comment by chrisbra** [comment]
Am 2015-06-15 08:00, schrieb jungle-boogie:
> I may have closed this a bit too soon, sorry.
> 
> If you take my small sample above and :Sort! n, the results:
> 
> 96.21
>  77.52
>  70.75
>  9.95
>  8.75
>  8.65
>  8.05
>  8
>  7.85
>  7.70
>  7.20
>  7.10
>  numbers
> 
> If I make that 8 read 8.00, it will sort correctly:
>  96.21
>  77.52
>  70.75
>  9.95
>  8.75
>  8.65
>  8.05
>  8.00
>  7.85
>  7.70
>  7.20
>  7.10
>  numbers
> 

I don't see a difference in the ordering.

**Comment by jungle-boogie** [comment]
Hello,
>I don't see a difference in the ordering.

You're right, I don't either. I don't know what I was observing so it looks fine!

Thanks a million for the plugin!

**Comment by jungle-boogie** [comment]
Hello,

So this is a problem...

Sort think this is correct:
PF
PG
PP
PQ
Pacific

Pacific should because before all others.

**Comment by chrisbra** [comment]
Hi jungle-boogie!

On Mo, 15 Jun 2015, jungle-boogie wrote:

> Hello,
> 
> So this is a problem...
> 
> Sort think this is correct:
> PF
> PG
> PP
> PQ
> Pacific
> 
> Pacific should because before all others.

Try the 'i' flag to the :Sort command

Best,
Christian
-- 
Freude beruht auf dem frohen Glauben, daß das Gute überwiegt.

**Comment by jungle-boogie** [comment]
Hi Christian,

> Try the 'i' flag to the :Sort command

You have everything figured out! That worked. I'll just have to keep track of these options.

Thanks,
Sean
