### ISSUE TITLE
CSVMax value function

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#60]
Hello,

Once the sort feature is corrected, could there be a feature to show the top values of a given column.
For instance, CSVAnalyze wouldn't show a large number like 10000 in its report if it only appears once.

Thanks,
j.b.

**Comment by chrisbra** [comment]
Am 2015-06-15 04:05, schrieb jungle-boogie:
> Hello,
> 
> Once the sort feature is corrected, could there be a feature to show
> the top values of a given column.
>  For instance, CSVAnalyze wouldn't show a large number like 10000 in
> its report if it only appears once.
> 

Okay, makes sense. I presume, a :Min function could be useful as well?

**Comment by jungle-boogie** [comment]
Hello,
>Okay, makes sense. I presume, a :Min function could be useful as well?

Good idea!

**Comment by chrisbra** [comment]
Should be there now.

**Comment by jungle-boogie** [comment]
:+1:
