### ISSUE TITLE
Basic pivot table with csv.vim?

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#61]
Hello,

Can csv.vim create a pivot table that you would make in MS Excel?
Group by column 1 and then count occurrences in column 2.

data and example here:
https://gist.github.com/jungle-boogie/8ba3551519f21e04c99c

**Comment by chrisbra** [comment]
Hi jungle-boogie!

On Do, 25 Jun 2015, jungle-boogie wrote:

> Hello,
> 
> Can csv.vim create a pivot table that you would make in MS Excel?
> Group by column 1 and then count occurrences in column 2.
> 
> data and example here:
> https://gist.github.com/jungle-boogie/8ba3551519f21e04c99c

I think, this is slightly out of scope for this plugin.

I don't even know how to make a command for that, that would be flexible 
enough for that kind.

Best,
Christian
-- 
Man verdirbt unter Leuten, die einen nicht übertreffen.
		-- Jean Paul

**Comment by jungle-boogie** [comment]
Hi Christian,

> I think, this is slightly out of scope for this plugin.

Fair enough. It does seem like a big under taking that may result in vim crashes and whatnot.

I'll stick with awk for this but if you consider something similar, I can try it out.
