### ISSUE TITLE
Have :UnArrange delete trailing whitespace?

### ISSUE THREAD

**Issue by SuperFluffy** [chrisbra/csv.vim#62]
When calling `:1,$ArrangeColumn`, inserting some next text into some fields (especially containing trailing whitespace), and then calling `2,$UnArrangeColulmn`, the trailing whitespace is not deleted. For example, take the following `csv`:
```
foo,bar,baz
1,2,3
```

When I arrange the columns, and insert some whitespace after 2, and un-arrange them, this will be the result:
```
foo,bar,baz
1,2  ,3
```

Is it possible to consider and delete all trailing whitespace? It is not always obvious to me which types of whitespace `csv.vim` considers when `:UnArrange`ing the columns. Note that I have my vim set to expand all tabs to spaces.

My impression is that `csv.vim` indeed works with tabs when arranging the columns, which might be the reason for this behaviour (just that they are hidden from me due to my settings).

**Comment by chrisbra** [comment]
Am 2015-06-30 17:42, schrieb Richard Janis Beckert:
> When calling :1,$ArrangeColumn, inserting some next text into some
> fields (especially containing trailing whitespace), and then calling
> 2,$UnArrangeColulmn, the trailing whitespace is not deleted. For
> example, take the following csv:
> 
> foo,bar,baz
> 1,2,3
> 
> When I arrange the columns, and insert some whitespace after 2, and
> un-arrange them, this will be the result:
> 
> foo,bar,baz
> 1,2 ,3
> 
> Is it possible to consider and delete all trailing whitespace? It is
> not always obvious to me which types of whitespace csv.vim considers
> when :UnArrangeing the columns. Note that I have my vim set to expand
> all tabs to spaces.
> 
> My impression is that csv.vim indeed works with tabs when arranging
> the columns, which might be the reason for this behaviour (just that
> they are hidden from me due to my settings).

Would you like this configurable or should it always delete trailing 
whitespace
in front of the next delimiter?

Best,
Christian

**Comment by SuperFluffy** [comment]
I don't know if trailing whitespace ever contains any information value, so
I wouldn't mind if always removing it was the default and only method. I
was initially surprised to find all that whitespace out of a sudden. :-)

Also, can you remove extra whitespace to the left *and* to the right of
every delimiter?

**Comment by chrisbra** [comment]
Should work now. Please test.

**Comment by SuperFluffy** [comment]
Perfect, exactly what I needed/wanted! This makes it so much nicer editing `csv` files in vim! Thanks a ton!
