### ISSUE TITLE
ArrangeColumn: `Error: getting Column Width, using default!` when last column contains empty field

### ISSUE THREAD

**Issue by SuperFluffy** [chrisbra/csv.vim#64]
Take the following sample csv:
```
foo,bar,baz
1,2,3
3,2,
foo,bar,baz
```

Since the third column in the third line contains no value, `csv.vim` will report the following warning:
```
CSV: Error: getting Column Width, using default!
```

Is it possible to simple ignore the empty field or treat it as having a width of `0` when calculating the max width of a column?

**Comment by chrisbra** [comment]
Thanks, please check latest version and confirm it is working.

**Comment by SuperFluffy** [comment]
Perfect, thanks for the fix!
