### ISSUE TITLE
`:ArrangeColumn` with left align makes syntax confused about delimiters

### ISSUE THREAD

**Issue by jjaderberg** [chrisbra/csv.vim#66]
I just installed your plugin and it looks excellent. I see minor unexpected behavior with regards to how the syntax file handles the delimiter char when it occurs within a quoted string after arranging columns with left alignment. Here's what I see, FWIW.

    "Issue ID","Owner","Created"
    0,"jjaderberg","2015-07-28"
    1,"jjaderberg,chrisbra","2015-07-28"

With a file like above, I note the following.

1. `:%ArrangeColumn` works as expected.
    ```
"Issue ID"|               "Owner"|    "Created"
             0|          "jjaderberg"| "2015-07-28"
             1| "jjaderberg,chrisbra"| "2015-07-28"
    ```

2. `let b:csv_arrange_align='lll'|%ArrangeColumn` correctly arranges the column but the comma in the second field of the second data row is concealed as if it were a field delimiter. There is also additional white space after the field content.
    ```
"Issue ID"  |"Owner"                |"Created"     
0           |"jjaderberg"           |"2015-07-28"  
1           |"jjaderberg|chrisbra"  |"2015-07-28"  
    ```
3. Subsequent invocations of `:%ArrangeColumn!` adds 'padding' white space to all fields. If I `:let b:csv_arrange_align='ccc'` or `='rrr'` or `=''` it does not realign the data, just adds more white space. Where the white space is added differs with how I set `b:csv_arrange_align` but the connection is not obvious.
4. If I delete the buffer, reopen the file and do `:%ArrangeColumn|let b:csv_arrange_align='lll'|%ArrangeColumn!` the columns are first arranged and right aligned (default, expected) but the second invocation does not left align the columns, only conceals the quoted comma and pads the fields with white space.
5. With the cursor on the concealed comma
    - `echo synIDattr(synIDtrans(synID(line("."),col("."),1)),"name")` says "Conceal"
    - `echo synIDattr(synID(line("."),col("."),1),"name")` says "CSVDelimiter"

So it seems setting `b:csv_arrange_align='lll'` and using the `:ArrangeColumn` command makes the syntax file confused about which commas are delimiters and which are not. It breaks subsequent invocations of the command. I haven't tried any of the more advanced functionality so I don't know if it has any other effects–if I see anything I'll try to update the issue, but this is as far as I can look right now.

**Comment by chrisbra** [comment]
Hi jjaderberg!

On Di, 28 Jul 2015, jjaderberg wrote:

> I just installed your plugin and it looks excellent. I see minor unexpected behavior with regards to how the syntax file handles the delimiter char when it occurs within a quoted string after arranging columns with left alignment. Here's what I see, FWIW.
> 
>     "Issue ID","Owner","Created"
>     0,"jjaderberg","2015-07-28"
>     1,"jjaderberg,chrisbra","2015-07-28"
> 
> With a file like above, I note the following.
> 
> 1. `:%ArrangeColumn` works as expected.
>     ```
> "Issue ID"|               "Owner"|    "Created"
>              0|          "jjaderberg"| "2015-07-28"
>              1| "jjaderberg,chrisbra"| "2015-07-28"
>     ```
> 
> 2. `let b:csv_arrange_align='lll'|%ArrangeColumn` correctly arranges the column but the comma in the second field of the second data row is concealed as if it were a field delimiter. There is also additional white space after the field content.
>     ```
> "Issue ID"  |"Owner"                |"Created"     
> 0           |"jjaderberg"           |"2015-07-28"  
> 1           |"jjaderberg|chrisbra"  |"2015-07-28"  
>     ```
> 3. Subsequent invocations of `:%ArrangeColumn!` adds 'padding' white space to all fields. If I `:let b:csv_arrange_align='ccc'` or `='rrr'` or `=''` it does not realign the data, just adds more white space. Where the white space is added differs with how I set `b:csv_arrange_align` but the connection is not obvious.
> 4. If I delete the buffer, reopen the file and do `:%ArrangeColumn|let b:csv_arrange_align='lll'|%ArrangeColumn!` the columns are first arranged and right aligned (default, expected) but the second invocation does not left align the columns, only conceals the quoted comma and pads the fields with white space.
> 5. With the cursor on the concealed comma
>     - `echo synIDattr(synIDtrans(synID(line("."),col("."),1)),"name")` says "Conceal"
>     - `echo synIDattr(synID(line("."),col("."),1),"name")` says "CSVDelimiter"
> 
> 
> So it seems setting `b:csv_arrange_align='lll'` and using the `:ArrangeColumn` command makes the syntax file confused about which commas are delimiters and which are not. It breaks subsequent invocations of the command. I haven't tried any of the more advanced functionality so I don't know if it has any other effects–if I see anything I'll try to update the issue, but this is as far as I can look right now.

Thanks for your feedback.

That is an interesting finding. Unfortunately, this is getting more and 
more complex :(

I will check, if there is a simple solution.

Best,
Christian
-- 
Toren besuchen im fremden Land die Museen, Weise gehen in die
Tavernen.
		-- Erich Kästner

**Comment by chrisbra** [comment]
can you please check current head? It doesn't fix the syntax highlighting issue, but the issue about changing the alignment should be fixed. You need to use :ArrangeCol! (e.g. you need the bang attribute)

**Comment by jjaderberg** [comment]
I have little experience with `git`–I did `git pull` in the plugin root directory and it indicates

> 2 files changed, 79 insertions(+), 120 deletions(-)

Is that the correct procedure to get the current head?

It looks good, I am now able to align and realign with `b:csv_arrange_align` and `:ArrangeColumn!`. Also, subsequent calls no longer add additional space.

I do see that the space padding is inconsistent between the alignments–right and center aligned columns keep a single space between the widest field's content and it's left field separator, whereas left aligned columns keep two spaces to the right of the content. If I remove the two trailing spaces in a left aligned field the syntax matcher correctly ignores a comma within quotes and does not highlight it as a `CSVDelimiter`.
