### ISSUE TITLE
Sort ignoring lesser values in ascending order

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#68]
Hello,

Using this sample data:
http://www.sharecsv.com/s/9096d32f98aa0ac671a1cca16fa43be8/SalesJan2009.csv

I can sort largest to smallest with `:Sort! n` on the price column, but `:Sort!` doesn't seem to correctly go in ascending order, as I would expect it.

If you sort on the header, "13,000" is first followed by 1200, skipping lesser values like 250. 

Is this expected?

Thanks!

**Comment by chrisbra** [comment]
Hi jungle-boogie!

On Mo, 17 Aug 2015, jungle-boogie wrote:

> Hello,
> 
> Using this sample data:
> http://www.sharecsv.com/s/9096d32f98aa0ac671a1cca16fa43be8/SalesJan2009.csv
> 
> I can sort largest to smallest with `:Sort! n` on the price column, but `:Sort!` doesn't seem to correctly go in ascending order, as I would expect it.
> 
> If you sort on the header, "13,000" is first followed by 1200, skipping lesser values like 250. 
> 
> Is this expected?

The default without the 'n' flag does not a numeric sort but an 
alphabetic sort. So you probably want :Sort n to sort numbers in 
ascending order.

Best,
Christian
-- 
Nur der ist weise, der weiß, daß er es nicht ist.
		-- Sokrates (470-399 v.Chr.)

**Comment by jungle-boogie** [comment]
Hi,

> So you probably want :Sort n to sort numbers in ascending order.

Yes, that's perfect!

Thanks!
