### ISSUE TITLE
CSVAddColumn not respecting cursor location or column number argument

### ISSUE THREAD

**Issue by shmup** [chrisbra/csv.vim#69]
A simple `:CSVAddColumn` is always appending a column at the end, regardless of where my cursor is.

And also if I do a `:CSVAddColumn 1` it still appends a column at the end.

For the sake of seeing if any arguments work, `:CSVAddColumn 1 3` does append 3 new columns.

**Comment by chrisbra** [comment]
Hi Jared!

On Sa, 26 Sep 2015, Jared Miller wrote:

> A simple `:CSVAddColumn` is always appending a column at the end, regardless of where my cursor is.
> 
> And also if I do a `:CSVAddColumn 1` it still appends a column at the end.

Hm, I can't reproduce this problem. This seems to work okay for me. Can 
you show me a sample file?

Best,
Christian
-- 
Wie man sein Kind nicht nennen sollte: 
  Rolf Fläche

**Comment by chrisbra** [comment]
unreproducable
