### ISSUE TITLE
Is it possible to define the headerline as the second line after any comments that might occur at the beginning of the file?

### ISSUE THREAD

**Issue by joelostblom** [chrisbra/csv.vim#71]
First of all, thank you for an amazing plugin! `csv.vim` lets me work with simple csv-files faster than any spreadsheet program ever did.

I just discovered the commenting feature, which I think is great. In some .csv files, I want to take a few notes in the beginning of the file followed by a blank line and then the header line. I would still like the highlighting of the header line and the column-wise functions to work correctly, effectively ignoring any comments in the beginning of the file for these operations, but still leaving the comments visible.

Is there a setting I can use to define the second line after the last commented line to be the header line? I tried `:let b:csv_headerline`, but could not get it to work correctly.

Example:
```
# This file contains this and that
# Some more comments

Col1,Col2,Col3
row1,row1,row1,
row2,row2,row2
```

**Comment by chrisbra** [comment]
I do personally not use comments, however it seems possible what you want:

![csv_header](https://cloud.githubusercontent.com/assets/244927/11249870/c45041a6-8e29-11e5-8687-554b4c557d1e.PNG)

This is just  `:let b:csv_headerline=4` and `:let g:csv_comment='#' and afterwards reinitializing using `:CSVInit`

**Comment by chrisbra** [comment]
BTW: Thanks for the really nice feedback. I appreciate it.

**Comment by joelostblom** [comment]
Sorry, I should have been clearer. I noticed I can have any line as the header line statically, but I didn't see an option to dynamically set it individually for each file. I guess maybe it is as simple as writing a small script in `.vimrc`?

**Comment by chrisbra** [comment]
Hi joelostblom!

On Mi, 18 Nov 2015, joelostblom wrote:

> Sorry, I should have been clearer. I noticed I can have any line as
> the header line statically, but I didn't see an option to dynamically
> set it individually for each file. I guess maybe it is as simple as
> writing a small script in `.vimrc`? 

Setting a variable with the 'b:' prefix means, it is only set for the 
current buffer and does not affect other buffers. So you can have two 
files one with b:csv_headerline=1 and the second with b:csv_headerline=5 
and it should just work.

Best,
Christian
-- 
Sorge nicht, wohin dich der einzelne Schritt führt: Nur wer weit
blickt, findet sich zurecht.
		-- Dag Hammarskjöld

**Comment by joelostblom** [comment]
Maybe I am misunderstanding, but doesn't your approach mean that I would need to type `b:csv_headerline=` manually every time I open a new file?

I am wondering if it is possible to have vim detect the number of commented lines in the beginning of a csv file and then automatically set `csv_headerline` to a suitable value for that file (in my case, the last commented line + one blank line).

**Comment by chrisbra** [comment]
Hi joelostblom!

On Mi, 18 Nov 2015, joelostblom wrote:

> Maybe I am misunderstanding, but doesn't your approach mean that I
> would need to type `b:csv_headerline=` manually every time I open a
> new file?
> 
> I am wondering if it is possible to have vim detect the number of
> commented lines in the beginning of a csv file and then automatically
> set `csv_headerline` to a suitable value for that file (in my case,
> the last commented line + one blank line).

Ah, now I got you. Hm, we could try to automate this.

Best,
Christian
-- 
Nie verzeiht dir eine Frau, daß sie dir etwas verzeihen muß.
		-- Maria Schell

**Comment by joelostblom** [comment]
Thanks, let me know if there is an easy solution, but don't worry if it is complicated. One could argue that it is good practice for me to standardize my csv-files to always have 3 lines of comments or something like that instead =)

**Comment by joelostblom** [comment]
With some help from StackOverflow, I added the following to my `.vimrc`:

```vim
    " Detect comments and identify the header line in csv-files                                                                                                                                                         
    autocmd Filetype csv /^[^#] " Place cursor on first non-comment line                                                                                                                                                 
    autocmd Filetype csv let b:csv_headerline=line('.') " Set cursor line as csv_headerline                                                                                                                              
    autocmd Filetype csv CSVInit " Update vim.csv plugin to be aware of the new headerline                                                                                                                               
```
   
(When passing these commands directly to `vim -c` I had to write `line('.')+1`, not sure why).

So far it is working with both only commented lines in the beginning of the file and a mix of commented lines and empty lines (limited testing)!

**Comment by chrisbra** [comment]
Okay, I have pushed a fix. Please test.

On Do, 19 Nov 2015, joelostblom wrote:

> With some help from StackOverflow, I added the following to my `.vimrc`:

I saw your question there, but haven't looked at it yet.


Best,
Christian
-- 
Geld korrumpiert - vor allem jene, die es nicht haben.
		-- Sir Peter Ustinov
