### ISSUE TITLE
something is broken...

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#74]
Hello,

Here's a sample file:
https://gist.githubusercontent.com/jungle-boogie/eef783ac0d33ec8d57e3/raw/4aa192e205b587887946e50f7e9e869fc342137f/tips.csv

When I open this file up, the whole file is red like its apart of the header. I cannot `:Sum` the fields with numbers because the results are all 0.

I'm using csv.vim from master.

**Comment by jungle-boogie** [comment]
Here's another example but much worse:
https://gist.githubusercontent.com/jungle-boogie/f81eb31b5292e19367fd/raw/1fbbf30d204c022a5083d94ebcffcc7bd57c38c7/gistfile1.txt

    "sacramentocrimeJanuary2006.csv" 7585L, 793575C
    Error detected while processing function <SNR>55_CheckSaneSearchPattern:
    line   44:
    E363: pattern uses more memory than 'maxmempattern'
    Interrupted
    Error detected while processing /usr/home/sean/.vim/bundle/csv.vim/syntax/csv.vim:
    line  165:
    Interrupted
    Interrupt: Press ENTER or type command to continue

**Comment by jbkopecky** [comment]
Hello,

I have the exact same issues.

Thank you for this great pluggin !

JB

**Comment by chrisbra** [comment]
what are your configuration values for the plugin?

**Comment by chrisbra** [comment]
Ah, okay the pattern needs to be correctly escaped. Should work now again.

**Comment by jbkopecky** [comment]
I have only set 
``` let g:csv_headerline=0 ```
https://github.com/jbkopecky/dotfiles/blob/master/vimrc#L372

( I have checked that filetype plugin line is before syntax on: these two options are handled by vim plug)

I'll try to reproduce with a minimal vimrc and simple csv to make sure it is not because of an other plugin interfeering

**Comment by jbkopecky** [comment]
Awesome, the last commit fixed it ! Thanks !
