### ISSUE TITLE
Invalid Column Pattern - Annoying Error

### ISSUE THREAD

**Issue by rgrinberg** [chrisbra/csv.vim#75]
I'm getting the following error on a CSV file with columns that include a `*` character

```
CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)
```

Anything that can be done about this? It's a bit annoying.

**Comment by chrisbra** [comment]
Am 2015-12-15 04:05, schrieb Rudi Grinberg:
> I'm getting the following error on a CSV file with columns that
> include a * character
> 
> CSV Syntax:Invalid column pattern, using default pattern
> \%([^,]*,\|$\)
> 
> Anything that can be done about this? It's a bit annoying.

Can you show me an example file?

**Comment by rgrinberg** [comment]
Sure, https://gist.github.com/rgrinberg/4b6141887a849743f489

**Comment by chrisbra** [comment]
I am afraid I don't see this error. Have you checked `:h csv-syntax-error`?
