### ISSUE TITLE
help with solarized theme and column colors

### ISSUE THREAD

**Issue by mellery451** [chrisbra/csv.vim#76]
I'm using solarized theme with vim in iterm2. I have loaded the solarized palette for my terminal as well.

For some reason, the even/odd column highlights don't seem to display properly (or at least they are not different...).  Can someone help me diagnose why this is happening?

<img width="957" alt="screen shot 2016-01-06 at 3 10 57 pm" src="https://cloud.githubusercontent.com/assets/463430/12157636/fb6949ec-b487-11e5-8c20-2dca16a7436f.png">

Thanks.

**Comment by chrisbra** [comment]
Does the help at `:h csv-syntax` help you?

**Comment by mellery451** [comment]
I guess the syntax-highlighting groups are want I'd want to try - but I gave up on solarized anyhow since it had other issues with it (like Error highlights not showing up). Thanks for the tip and thanks for this plugin (super useful).
