### ISSUE TITLE
airline show name of b:csv_headerline instead of first line

### ISSUE THREAD

**Issue by wsfreund** [chrisbra/csv.vim#78]
Hi there,

really nice plugin! Thanks a lot!

So, I was trying to use it on a file in which the csv header is offset in the 15th line. I've commented the previous lines so that it can detect that the b:csv_headerline is 15, however, if I set it on airline to display the field names, I was getting a error.

Instead of getting the first line, I've changed line 482 to give the buffer header:

let head  = split(getline(getbufvar("%","csv_headerline",1)),b:col.'\zs')

Maybe you want to add this or something similar to the plugin.

Thanks!

**Comment by wsfreund** [comment]
Another interesting change is on MaxCol function: instead of starting on the first line, it could start on the header line which can be set by the user. I've changed line 510 on MaxColumn:

let i = this_col ? a:1 : getbufvar("%","csv_headerline",1)

With this, I can see the airline correctly displayed by only changing the b:csv_headerline to the correct line: 

![schnappschuss 2016-02-08 04 18 22](https://cloud.githubusercontent.com/assets/51397/12879494/144bcd16-ce1b-11e5-8168-870aded0adf7.png)

**Comment by chrisbra** [comment]
Hi Werner!

On So, 07 Feb 2016, Werner Freund wrote:

> Another interesting change is on MaxCol function: instead of starting on the first line, it could start on the header line which can be set by the user. I've changed line 510 on MaxColumn:
> 
> let i = this_col ? a:1 : getbufvar("%","csv_headerline",1)
> 
> With this, I can see the airline correctly displayed by only changing the b:csv_headerline to the correct line: 
> 
> ![schnappschuss 2016-02-08 04 18 22](https://cloud.githubusercontent.com/assets/51397/12879494/144bcd16-ce1b-11e5-8168-870aded0adf7.png)

Thanks! I just pushed a fix.

Best,
Christian
-- 
Je kaputter die Welt draußen, desto heiler muß sie zu Hause sein.
		-- Reinhard Mey
