### ISSUE TITLE
Opening new "tsv" file results in stall

### ISSUE THREAD

**Issue by jeetsukumaran** [chrisbra/csv.vim#81]
To replicate:

    vim x.tsv 

Vim stalls until Ctrl-C is issued.

**Comment by chrisbra** [comment]
I don't see this. Please run `vim -V20foobar.log x.tsv` and make the logfile foobar.log available somewhere.

**Comment by jeetsukumaran** [comment]
[foobar.log.zip](https://github.com/chrisbra/csv.vim/files/153355/foobar.log.zip)

**Comment by chrisbra** [comment]
What is this:
` autocommand :call <SID>_reset_csv_delimiter('\t')`

**Comment by jeetsukumaran** [comment]
It is from my vimrc:
~~~
let g:csv_delim = '\t\|,'
function! s:_reset_csv_delimiter(new_delimiter)
    :%UnArrangeColumn
    let old_delim = get(b:, "delimiter", ",")
    let b:delimiter = a:new_delimiter
    let b:col=substitute(b:col, old_delim, b:delimiter, 'g')
    " echomsg "Resetting delimiter from '" . old_delim . "' to '" . b:delimiter . "'"
    :InitCSV!
    :%ArrangeColumn
endfunction
command! -nargs=1 CsvDelimiterReset :call <SID>_reset_csv_delimiter(<q-args>)
if has("autocmd")
    augroup vimrc_resetcsvdelimiter
        autocmd!
        autocmd BufNewFile,BufFilePre,BufRead *.tsv :call <SID>_reset_csv_delimiter('\t')
    augroup END
endif
hi CSVColumnEven        guibg=#333330
hi CSVColumnHeaderEven  guibg=#111110
hi CSVColumnOdd         guibg=#304444
hi CSVColumnHeaderOdd   guibg=#002222
let g:csv_autocmd_arrange      = 1
let g:csv_autocmd_arrange_size = 1024*1024
~~~

**Comment by chrisbra** [comment]
If you remove the autocommand, does it still hang?

**Comment by jeetsukumaran** [comment]
No it does not! What's more, it avoids the stripping of delimiters reported in https://github.com/chrisbra/csv.vim/issues/82 .

Hmmm ... what am I doing wrong with the autocmd?

**Comment by chrisbra** [comment]
I don't know. I couldn't reproduce this issue.

**Comment by jeetsukumaran** [comment]
I have removed all "startup" customizations, and things appear to work. The only issue is that when creating a new TSV file (as opposed to CSV), I have to reopen the file after the first columns have been inserted for the columns to be recognized. No need to do this with CSV.
