### ISSUE TITLE
Saving file results in delimiters being stripped

### ISSUE THREAD

**Issue by jeetsukumaran** [chrisbra/csv.vim#82]
Any file, new or existing, upon writing and exiting, results in delimiters being stripped.

**Comment by chrisbra** [comment]
I don't see this? Are you talking about all delimiters or trailing ones?

**Comment by jeetsukumaran** [comment]
All delimiters. E.g.,
~~~
a,1,1
b,2,2
~~~
becomes:
~~~
a11
b22
~~~

**Comment by chrisbra** [comment]
Hm, what is the output of
`:au BufWritePost,BufWritePre`

**Comment by jeetsukumaran** [comment]
This:
~~~
::au BufWritePost,BufWritePre
--- Auto-Commands ---
CSV_Edit  BufWritePost
    *.csv     :exe printf(":call CSVArrangeCol(1, %d, 0, %d)", line('$'), get(g:, 'csv_autocmd_arrange_size', -1))
    *.dat     :exe printf(":call CSVArrangeCol(1, %d, 0, %d)", line('$'), get(g:, 'csv_autocmd_arrange_size', -1))
    *.tsv     :exe printf(":call CSVArrangeCol(1, %d, 0, %d)", line('$'), get(g:, 'csv_autocmd_arrange_size', -1))
    *.tab     :exe printf(":call CSVArrangeCol(1, %d, 0, %d)", line('$'), get(g:, 'csv_autocmd_arrange_size', -1))
CtrlPMRUF  BufWritePost
    *         cal s:record(expand('<abuf>', 1))
Undotree  BufWritePost
    *         call UndotreeUpdate()
BuffergatorMRU  BufWritePost
    *         call BuffergatorUpdateMRU(expand('<abuf>'))
gzip  BufWritePost
    *.gz      call gzip#write("gzip")
    *.bz2     call gzip#write("bzip2")
    *.Z       call gzip#write("compress -f")
    *.lzma    call gzip#write("lzma -z")
    *.xz      call gzip#write("xz -z")
vimrc_striptrailingwhitespace  BufWrite
    *         :call jeetlib#whitespace#StripTrailingWhitespace()
CSV_Edit  BufWrite
    *.csv     :sil %UnArrangeColumn
    *.dat     :sil %UnArrangeColumn
    *.tsv     :sil %UnArrangeColumn
    *.tab     :sil %UnArrangeColumn 
~~~

**Comment by chrisbra** [comment]
If you call `:%UnArrangeColumn` and then `:%ArrangeCol` does that also strip the delimiter?

**Comment by chrisbra** [comment]
Just to make sure, it's not the concealing, that you are seeing, right?

**Comment by jeetsukumaran** [comment]
It looks like ``:%UnArrangeColumn`` does indeed strip the delimiter. And no, its not the concealing, as a raw dump of the file shows the delimiter missing.

**Comment by chrisbra** [comment]
Hm, this looks wrong:
```
let g:csv_delim = '\t\|,'
```
this is not meant to be a regular expression, but rather a delimiter to use. I am not surprised this breaks in subtle ways. You could try 
`let g:csv_delim = '\%(\t\|,\)'` which seems to work for this particular use case, but it might still break

**Comment by jeetsukumaran** [comment]
As noted in https://github.com/chrisbra/csv.vim/issues/81, this seems to be an issue with my setting the delimiter. 

I will try your suggestion

**Comment by jeetsukumaran** [comment]
Changing `t\|,` to `'\%(\t\|,\)'` results in the file being stripped of delimiters even without the autocmd

**Comment by jeetsukumaran** [comment]
I have removed all "startup" customizations, and things appear to work. The only issue is that when creating a new TSV file (as opposed to CSV), I have to reopen the file after the first columns have been inserted for the columns to be recognized. No need to do this with CSV.
