### ISSUE TITLE
Neovim freezes when opening an empty file

### ISSUE THREAD

**Issue by eliangcs** [chrisbra/csv.vim#83]
First of all, thanks for the great work!

I'm using csv.vim with neovim and I found it seems to freeze my neovim whenever I open an empty CSV:

```
$ touch empty.csv
$ nvim empty.csv
```

Then in the neovim status line shows "CSV: No delimiter found. See :h csv-delimiter to set it manually!" and I can't do anything except for killing neovim by force.

**Comment by chrisbra** [comment]
Does it happen with vim? If not, I believe this is a neovim issue (and I have never seen such issue with csv.vim)

**Comment by chrisbra** [comment]
BTW: Ctrl-C should always abort csv.vim

**Comment by eliangcs** [comment]
I don't know why, but the issue is gone after I update all my plugins. Thanks!
