### ISSUE TITLE
:DuplicateColumn?

### ISSUE THREAD

**Issue by lkraav** [chrisbra/csv.vim#84]
I was looking to create a copy of a column. Apparently `:Transpose`, `yyp`, `:Transpose` seems to be the only way to do this. Am I missing something? Should there be a `:DuplicateColumn` functionality, or perhaps a switch to `:AddColumn` that makes it copy the the currently active column to the new one?

**Comment by chrisbra** [comment]
Yeah, this hasn't been requested yet. Will implement it then.
