### ISSUE TITLE
feature request: average support in csv.vim

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#85]
Hi,

I see the one could create new functions within csv.vim, such as average, but have you considered adding that to the core of this plug-in itself?

Sum is supported so IMO, average would be a very useful function to support.

Thanks,
sean

**Comment by chrisbra** [comment]
It's not done, because until now I hadn't a need for it (unlike the Sum function) and nobody has asked for it.

**Comment by jungle-boogie** [comment]
I would personally use it, but if it's too much to add, then that's okay.

**Comment by chrisbra** [comment]
> I would personally use it, but if it's too much to add, then that's 
> okay.

I'll add it then. But please be patient, I don't have much time 
currently.

**Comment by chrisbra** [comment]
I just noticed, I do use an avg function. It's described in the help at `:h csv-aggregate-functions`

However, I just begun implementing this, but it is more work than expected, so for now use please use the way described in the help until this is supported out of the box.

**Comment by jungle-boogie** [comment]
Made any progress on this feature?

**Comment by chrisbra** [comment]
I haven't looked at it again, since there is a working solution in the help. I haven't forgotten about it, but it just slipped down in my personal todo list.
