### ISSUE TITLE
suggestion: Display the name of the analyzed column in the results

### ISSUE THREAD

**Issue by indera** [chrisbra/csv.vim#88]
Currently when you use :Analyze on a column you get 

```
Nr      Count    %      Value
=====================
01      08       9%     20160614
02      04       5%     2
03      23      26%     20160616
04      16      18%     20160615
05      15      17%     20160617
=====================
different values: 8
```

It would be great if we displayed something like

different values in **column XYZ**: 8

I should be just a small change in the AnalyzeColumn function:

1592 fu! <sid>AnalyzeColumn(...) "{{{3

```
1659     echo printf("%s", repeat('=', strdisplaywidth(title)))
1660     echo printf("different values: %d", len(count_items))
1661     unlet max_items

```

**Comment by indera** [comment]
Thank you @chrisbra for implementing this

**Comment by chrisbra** [comment]
Yes, for now I would leave it at the column number, because it could get too big and it there might not always be a name
