### ISSUE TITLE
can't get plugin to run

### ISSUE THREAD

**Issue by codeHatcher** [chrisbra/csv.vim#91]
plugin not running in my neovim installation, nor in my vim installation. Is there a way for me to run the plugin manually on an open file?

**Comment by codeHatcher** [comment]
it ends up looking like this btw
![image](https://cloud.githubusercontent.com/assets/5360982/18185893/9f6d9632-7054-11e6-9cd8-326ddddd1e8f.png)

**Comment by codeHatcher** [comment]
while I'm at it, here is the actual file

**Comment by codeHatcher** [comment]
hmm, I think it has something to do with the newline character. I think excel for osx puts a strange newline character that messes things up

**Comment by codeHatcher** [comment]
Confirmed, Excel on OSX still uses the archaic carriage return only. If possible, you could make sure the plugin considers that the same as a carriage return line feed. https://gist.github.com/jennybc/0be7717c2b5b30088811

**Comment by codeHatcher** [comment]
confirmed this issue as being due to saving my csv in Excel 2011 for OSX/Mac

**Comment by chrisbra** [comment]
I think you need to tweak your `'fileformats'` setting, or try to read it explicitly as `mac` format: `:e! ++ff=mac`
