### ISSUE TITLE
Fixed column width with empty fields

### ISSUE THREAD

**Issue by ckaldemeyer** [chrisbra/csv.vim#93]
Hi,

it might be a classic RTFM-question but I couldn't find any answer in the documentation.

If I have a csv-file with empty fields like this:

		cord@cord-Laptop:~/Programmierung/ENKF/simple_setup$ head nodes_flows_seq.csv
		class,ExtractionTurbine,Sink,BackpressureTurbine,Sink
		label,extr_turbine,electrical_demand,bp_turbine,heat_demand
		source,extr_turbine,electrical_balance,bp_turbine,heat_balance
		target,electrical_balance,electrical_demand,electrical_balance,heat_demand
		attribute,max,variable_costs,max,actual_value
		,0.97,-49.94,0.99,0.1469452338
		,0.97,-42.93,0.99,0.1500444621
		,0.97,-38.45,0.99,0.1569258683
		,0.97,-29.35,0.99,0.1740503842
		,0.97,-27.9,0.99,0.2175136794

And it looks like this: http://pasteboard.co/rRzV3ZxFk.png

How can I have a fixed columns with even if some fields are empty?

Thanks in advance!
Cord

**Comment by chrisbra** [comment]
i think that looks correct. What problem are you trying to solve?

**Comment by ckaldemeyer** [comment]
> i think that looks correct. What problem are you trying to solve?

Sorry, maybe I didn't describe it clearly..

In the first column, all rows after "attribute" are empty and the column has different widths depending of the content of a specific row (cell).

How can I have a fixed column width, even if some cells are empty e.g. all cells at the width of the longest cell in a column (in this case the lengh of the cell "attribute")?

**Comment by chrisbra** [comment]
Am 2016-11-24 10:41, schrieb Cord Kaldemeyer:
>> i think that looks correct. What problem are you trying to solve?
> 
> Sorry, maybe I didn't describe it clearly..
> 
> In the first column, all rows after "attribute" are empty and the
> column has different widths depending of the content of a specific row
> (cell).
> 
> How can I have a fixed column width, even if some cells are empty e.g.
> all cells at the width of the longest cell in a column (in this case
> the lengh of the cell "attribute")?
> 

Try the :ArrangeCol command

**Comment by ckaldemeyer** [comment]
Thanks for the hint which brought me to 

    let g:csv_autocmd_arrange = 1

which was exactly what I was searching for!
