### ISSUE TITLE
`CSV Syntax:Invalid column pattern` without a `:syn-on` statement

### ISSUE THREAD

**Issue by TMiguelT** [chrisbra/csv.vim#94]
I'm aware of `6.5 Syntax error when opening a CSV file` in the manual, however I don't have any `syn-on` statement in my `.vimrc`:

```bash
$ cat ~/.vimrc 
filetype plugin on
```

However if I open a CSV, it get the following error:
```
CSV Syntax:Invalid column pattern, using default pattern \%([^,]*,\|$\)
```

Is there any other reason this could happen? I'm on Ubuntu 16.10 with no other vim plugins installed. I installed csv.vim by downloading from [here](http://www.vim.org/scripts/download_script.php?src_id=22798) and running `:source %` on the vimball.

**Comment by chrisbra** [comment]
Am 2016-11-22 07:41, schrieb Michael Milton:
> I'm aware of 6.5 Syntax error when opening a CSV file in the manual,
> however I don't have any syn-on statement in my .vimrc:
> 
> $ cat ~/.vimrc
> filetype plugin on
> 
> However if I open a CSV, it get the following error:
> 
> CSV Syntax:Invalid column pattern, using default pattern
> \%([^,]*,\|$\)
> 
> Is there any other reason this could happen? I'm on Ubuntu 16.10 with
> no other vim plugins installed. I installed csv.vim by downloading
> from here [1] and running :source % on the vimball.

That error clearly comes from the syntax part of the plugin. I wonder
why it is loaded, if you have no syntax on. Hm perhaps /etc/vimrc
or something sets it?

Can you check the output of `:scriptnames` and `:syn`

**Comment by TMiguelT** [comment]
`:scriptnames`:
```
1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim74/debian.vim
  3: /usr/share/vim/vim74/syntax/syntax.vim
  4: /usr/share/vim/vim74/syntax/synload.vim
  5: /usr/share/vim/vim74/syntax/syncolor.vim
  6: /usr/share/vim/vim74/filetype.vim
  7: ~/.vim/ftdetect/csv.vim
  8: ~/.vimrc
  9: /usr/share/vim/vim74/ftplugin.vim
 10: ~/.vim/plugin/csv.vim
 11: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
 12: /usr/share/vim/vim74/plugin/gzip.vim
 13: /usr/share/vim/vim74/plugin/logiPat.vim
 14: /usr/share/vim/vim74/plugin/matchparen.vim
 15: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 16: /usr/share/vim/vim74/plugin/rrhelper.vim
 17: /usr/share/vim/vim74/plugin/spellfile.vim
 18: /usr/share/vim/vim74/plugin/tarPlugin.vim
 19: /usr/share/vim/vim74/plugin/tohtml.vim
 20: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 21: /usr/share/vim/vim74/plugin/zipPlugin.vim
 22: /usr/share/vim/vim74/scripts.vim
 23: ~/.vim/syntax/csv.vim
 24: ~/.vim/ftplugin/csv.vim
```

`:syn`:
```
:syn
--- Syntax items ---
CSVColumnHeaderOdd xxx match /\%<2l\%(\%(\%("\%([^"]\|""\)*"\s*\)\%(^I\|$\)\)\|\%([^^I]*\%(^I\|$\)\)\)/  contains=CSVDelimiter nextgroup=CSVColumnHeaderEven
                   links to WarningMsg
CSVColumnHeaderEven xxx match /\%<2l\%(\%(\%("\%([^"]\|""\)*"\s*\)\%(^I\|$\)\)\|\%([^^I]*\%(^I\|$\)\)\)/  contains=CSVDelimiter nextgroup=CSVColumnHeaderOdd
                   links to WarningMsg
CSVColumnOdd   xxx match /\%(\%(\%("\%([^"]\|""\)*"\s*\)\%(^I\|$\)\)\|\%([^^I]*\%(^I\|$\)\)\)/  contains=CSVDelimiter nextgroup=CSVColumnEven
                   links to DiffAdd
CSVColumnEven  xxx match /\%(\%(\%("\%([^"]\|""\)*"\s*\)\%(^I\|$\)\)\|\%([^^I]*\%(^I\|$\)\)\)/  contains=CSVDelimiter nextgroup=CSVColumnOdd
                   links to DiffChange
CSVDelimiter   xxx match /\%(\%(\%("\%([^"]\|""\)*"\)\%(^I\)\)\|\%([^^I]*\%(^I\)\)\)/ms=e,me=e  contained conceal
                   links to Conceal
CSVComment     xxx match +\V\/*\m.*\%(\V*\/\m\)\?+
                   links to Comment
```

Notably, in `/usr/share/vim/vimrc` I have the line:
```
" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif
```

Since this is the default Ubuntu vim configuration, should I be editing it? Or is there some workaround?

**Comment by chrisbra** [comment]
Am 2016-11-23 01:09, schrieb Michael Milton:
> :scriptnames:
> 
> 1: /usr/share/vim/vimrc
>   2: /usr/share/vim/vim74/debian.vim
>   3: /usr/share/vim/vim74/syntax/syntax.vim
>   4: /usr/share/vim/vim74/syntax/synload.vim
>   5: /usr/share/vim/vim74/syntax/syncolor.vim
>   6: /usr/share/vim/vim74/filetype.vim
>   7: ~/.vim/ftdetect/csv.vim
>   8: ~/.vimrc
>   9: /usr/share/vim/vim74/ftplugin.vim
>  10: ~/.vim/plugin/csv.vim
>  11: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
>  12: /usr/share/vim/vim74/plugin/gzip.vim
>  13: /usr/share/vim/vim74/plugin/logiPat.vim
>  14: /usr/share/vim/vim74/plugin/matchparen.vim
>  15: /usr/share/vim/vim74/plugin/netrwPlugin.vim
>  16: /usr/share/vim/vim74/plugin/rrhelper.vim
>  17: /usr/share/vim/vim74/plugin/spellfile.vim
>  18: /usr/share/vim/vim74/plugin/tarPlugin.vim
>  19: /usr/share/vim/vim74/plugin/tohtml.vim
>  20: /usr/share/vim/vim74/plugin/vimballPlugin.vim
>  21: /usr/share/vim/vim74/plugin/zipPlugin.vim
>  22: /usr/share/vim/vim74/scripts.vim
>  23: ~/.vim/syntax/csv.vim
>  24: ~/.vim/ftplugin/csv.vim
> 
> :syn:
> 
> :syn
> --- Syntax items ---
> CSVColumnHeaderOdd xxx match
> /\%<2l\%(\%(\%("\%([^"]\|""\)*"\s*\)\%(^I\|$\)\)\|\%([^^I]*\%(^I\|$\)\)\)/
>  contains=CSVDelimiter nextgroup=CSVColumnHeaderEven
>                    links to WarningMsg
> CSVColumnHeaderEven xxx match
> /\%<2l\%(\%(\%("\%([^"]\|""\)*"\s*\)\%(^I\|$\)\)\|\%([^^I]*\%(^I\|$\)\)\)/
>  contains=CSVDelimiter nextgroup=CSVColumnHeaderOdd
>                    links to WarningMsg
> CSVColumnOdd   xxx match
> /\%(\%(\%("\%([^"]\|""\)*"\s*\)\%(^I\|$\)\)\|\%([^^I]*\%(^I\|$\)\)\)/
> contains=CSVDelimiter nextgroup=CSVColumnEven
>                    links to DiffAdd
> CSVColumnEven  xxx match
> /\%(\%(\%("\%([^"]\|""\)*"\s*\)\%(^I\|$\)\)\|\%([^^I]*\%(^I\|$\)\)\)/
> contains=CSVDelimiter nextgroup=CSVColumnOdd
>                    links to DiffChange
> CSVDelimiter   xxx match
> /\%(\%(\%("\%([^"]\|""\)*"\)\%(^I\)\)\|\%([^^I]*\%(^I\)\)\)/ms=e,me=e
> contained conceal
>                    links to Conceal
> CSVComment     xxx match +\V\/*\m.*\%(\V*\/\m\)\?+
>                    links to Comment
> 
> Notably, in /usr/share/vim/vimrc I have the line:
> 
> " Vim5 and later versions support syntax highlighting. Uncommenting
> the next
> " line enables syntax highlighting by default.
> if has("syntax")
>   syntax on
> endif
> 
> Since this is the default Ubuntu vim configuration, should I be
> editing it? Or is there some workaround?

No, you should not modify /usr/share/vim/vimrc, since updates will 
silently overwrite those files.

It's better to put :syn off into your .vimrc if you don't want syntax 
highlighting.
