### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by TMiguelT** [chrisbra/csv.vim#95]
What are our thoughts on modernizing the documentation? I'm happy to do the work, I'd just like to see if it's agreed this is a good idea.

I'd like to
* Convert the README to markdown, so we can have built-in links and code blocks
* Add install instructions that include vim.org, using Vundle, building from source etc
* Refactor the changelog into a separate file (?)

Thoughts?

**Comment by chrisbra** [comment]
Am 2016-11-22 13:12, schrieb Michael Milton:
> What are our thoughts on modernizing the documentation? I'm happy to
> do the work, I'd just like to see if it's agreed this is a good idea.
> 
> I'd like to
> 
>  	* Convert the README to markdown, so we can have built-in links and
> code blocks
>  	* Add install instructions that include vim.org, using Vundle,
> building from source etc
>  	* Refactor the changelog into a separate file (?)
> 
> Thoughts?

Sounds reasonable. I'd appreciate help here. Thanks!

**Comment by jungle-boogie** [comment]
> Convert the README to markdown, so we can have built-in links and code blocks

I hate to be the opposite of change, but I personally like text files so I can read it in more/less/vim without seeing markdown code blocks.

**Comment by TMiguelT** [comment]
@jungle-boogie I see your point but if you want the help in a text format I think you should be using the vim help (`:h`) anyway. This seems to be a separate file to the README: https://github.com/chrisbra/csv.vim/blob/master/doc/ft-csv.txt

**Comment by TMiguelT** [comment]
Okay, I've done most of the work. What do we think about this:
https://github.com/TMiguelT/csv.vim/blob/master/README.md

I think the best part is the animated gif at the top!

**Comment by chrisbra** [comment]
Hi Michael!

On Do, 24 Nov 2016, Michael Milton wrote:

> Okay, I've done most of the work. What do we think about this:
> https://github.com/TMiguelT/csv.vim/blob/master/README.md
> 
> I think the best part is the animated gif at the top!

Very nice thanks you. Some notes:
- The vim-airline link is wrong, it should be vim-airline/vim-airline
- Something in the first code block here: 
  https://github.com/TMiguelT/csv.vim/blob/master/README.md#calculate-new-columns 
  is missing
- here 
  https://github.com/TMiguelT/csv.vim/blob/master/README.md#header-lines
  and here 
  https://github.com/TMiguelT/csv.vim/blob/master/README.md#vertical-folding
  you have `vim:VHeader 2` the vim looks wrong
- Some data uses still vim help highlighting, e.g. trailing ~ and `, 
  e.g. the part after: "consider this data:" here  
  https://github.com/TMiguelT/csv.vim/blob/master/README.md#transforming-into-a-table
- Average column is missing. I have probably caused this when I updated 
  the documentation yesterday. Sorry for that.
- That line of the Makefile: 
  https://github.com/TMiguelT/csv.vim/blob/master/Makefile#L41
  needs to be removed
- Perhaps move the changelog to a separate Changelog (don't need some 
  fancy highlighting there, it should be just for documentation 
  purposes)

Overall I really like the result. Thanks you very much.

Best,
Christian
-- 
Streusand her, da dreht einer durch.

**Comment by TMiguelT** [comment]
I've fixed the things you mentioned. Tell me if you find more issues.

I suppose the ongoing problem is going to be updating both this and the vim help file. Admittedly if you're only doing it one feature at a time it won't be so bad (like the average feature you added yesterday). The ideal solution would be writing a converter from the vim help format to markdown but that would be a nightmare. I hope the project is stable enough that this won't be a problem.

I think having a markdown readme will really help the visibility of the project, however.

**Comment by chrisbra** [comment]
Hi Michael!

On Do, 24 Nov 2016, Michael Milton wrote:

> I've fixed the things you mentioned. Tell me if you find more issues.
> 
> I suppose the ongoing problem is going to be updating both this and the vim help file. Admittedly if you're only doing it one feature at a time it won't be so bad (like the average feature you added yesterday). The ideal solution would be writing a converter from the vim help format to markdown but that would be a nightmare. I hope the project is stable enough that this won't be a problem.
> 
> I think having a markdown readme will really help the visibility of the project, however.

Yeah, I think I can handle it. There haven't been too many updates to 
the csv filetype, because I basically consider it feature complete.

Best,
Christian
-- 
Der Mensch ist gut und will nicht, daß man vor einem andern als ihm
selber krieche.
		-- Jean Paul
