### ISSUE TITLE
enable/disable csv.vim pluging

### ISSUE THREAD

**Issue by horida** [chrisbra/csv.vim#96]
It would be nice to have the possibility to disable csv.vim temporarily to have a look at the "raw" file.

Thanks

**Comment by chrisbra** [comment]
Hi horida!

On Do, 24 Nov 2016, horida wrote:

> It would be nice to have the possibility to disable csv.vim temporarily to have a look at the "raw" file.

Does :syn off do what you want?

**Comment by horida** [comment]
definitely!

Thanks for the fast answer and congrats to this project
