### ISSUE TITLE
Ability to left-align all columns

### ISSUE THREAD

**Issue by taylor-peterson** [chrisbra/csv.vim#99]
Is there a way to left-align all columns?
Best I can tell, I'd currently have to use ":let b:csv_arrange_align = 'lc.'" with as many "l"s as I have columns.

**Comment by chrisbra** [comment]
Yes, that is currently the only way

**Comment by taylor-peterson** [comment]
Any chance of an easier way?

(Thanks by the way for the unarrange fix. It works perfectly!)

**Comment by chrisbra** [comment]
Hi Taylor!

On Mi, 30 Nov 2016, Taylor Peterson wrote:

> Any chance of an easier way?

What would be easier?
Perhaps :ArrangeColumn with an additional argument which defines the 
arrangement? Like LR.
So :ArrangeColumn L
would left align all columns

Or :ArrangeColumn LC
will left align the first column, center aligne the second and the reset 
right align?

> 
> (Thanks by the way for the unarrange fix. It works perfectly!)

**Comment by taylor-peterson** [comment]
I think keeping the arrange setting separate like it currently is would be
best.

Perhaps use 'l*' to mean left align all columns.

Another approach would be to make the default alignment configurable.

**Comment by chrisbra** [comment]
Good idea. I just implemented it.

**Comment by taylor-peterson** [comment]
Thanks for the super-quick response!
